// src/app.ts
import express7 from "express";
import { toNodeHandler } from "better-auth/node";

// lib/auth.ts
import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";

// lib/prisma.ts
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";

// generated/prisma/client.ts
import * as path from "path";
import { fileURLToPath } from "url";

// generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.8.0",
  "engineVersion": "3c6e192761c0362d496ed980de936e2f3cebcd3a",
  "activeProvider": "postgresql",
  "inlineSchema": '// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\n// Get a free hosted Postgres database in seconds: `npx create-db`\n\ngenerator client {\n  provider = "prisma-client"\n  output   = "../generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\nenum Role {\n  STUDENT\n  TUTOR\n  ADMIN\n}\n\nenum BookingStatus {\n  CONFIRMED\n  COMPLETED\n  CANCELLED\n}\n\nmodel User {\n  id        String   @id @default(uuid())\n  name      String\n  email     String   @unique\n  password  String?\n  role      Role     @default(STUDENT)\n  isBanned  Boolean  @default(false)\n  createdAt DateTime @default(now())\n\n  tutorProfile TutorProfile?\n  bookings     Booking[]     @relation("StudentBookings")\n  reviews      Review[]\n\n  emailVerified Boolean   @default(false)\n  image         String?\n  updatedAt     DateTime  @updatedAt\n  sessions      Session[]\n  accounts      Account[]\n\n  phone  String?\n  status String? @default("ACTIVE")\n\n  @@map("users")\n}\n\nmodel TutorProfile {\n  id         String   @id @default(uuid())\n  userId     String   @unique\n  bio        String?\n  image      String?\n  hourlyRate Float\n  rating     Float    @default(0)\n  isApproved Boolean  @default(false)\n  createdAt  DateTime @default(now())\n\n  user User @relation(fields: [userId], references: [id])\n\n  categoryId String\n  category   Category @relation(fields: [categoryId], references: [id])\n\n  bookings     Booking[]      @relation("TutorBookings")\n  reviews      Review[]\n  availability Availability[]\n\n  @@map("tutor_profiles")\n}\n\nmodel Category {\n  id   String @id @default(uuid())\n  name String @unique\n\n  tutors TutorProfile[]\n\n  @@map("categories")\n}\n\nmodel Availability {\n  id        String @id @default(uuid())\n  tutorId   String\n  day       String // e.g. Monday\n  startTime String // "10:00"\n  endTime   String // "14:00"\n\n  tutor TutorProfile @relation(fields: [tutorId], references: [id])\n\n  @@map("availability")\n}\n\nmodel Booking {\n  id        String        @id @default(uuid())\n  studentId String\n  tutorId   String\n  date      String\n  time      String\n  status    BookingStatus @default(CONFIRMED)\n  createdAt DateTime      @default(now())\n\n  student User         @relation("StudentBookings", fields: [studentId], references: [id])\n  tutor   TutorProfile @relation("TutorBookings", fields: [tutorId], references: [id])\n\n  @@map("bookings")\n}\n\nmodel Review {\n  id        String   @id @default(uuid())\n  userId    String\n  tutorId   String\n  rating    Int\n  comment   String\n  createdAt DateTime @default(now())\n\n  user  User         @relation(fields: [userId], references: [id])\n  tutor TutorProfile @relation(fields: [tutorId], references: [id])\n\n  // one review per tutor per student\n\n  @@unique([userId, tutorId])\n  @@map("reviews")\n}\n\nmodel Session {\n  id        String   @id\n  expiresAt DateTime\n  token     String\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n  ipAddress String?\n  userAgent String?\n  userId    String\n  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  @@unique([token])\n  @@index([userId])\n  @@map("session")\n}\n\nmodel Account {\n  id                    String    @id\n  accountId             String\n  providerId            String\n  userId                String\n  user                  User      @relation(fields: [userId], references: [id], onDelete: Cascade)\n  accessToken           String?\n  refreshToken          String?\n  idToken               String?\n  accessTokenExpiresAt  DateTime?\n  refreshTokenExpiresAt DateTime?\n  scope                 String?\n  password              String?\n  createdAt             DateTime  @default(now())\n  updatedAt             DateTime  @updatedAt\n\n  @@index([userId])\n  @@map("account")\n}\n\nmodel Verification {\n  id         String   @id\n  identifier String\n  value      String\n  expiresAt  DateTime\n  createdAt  DateTime @default(now())\n  updatedAt  DateTime @updatedAt\n\n  @@index([identifier])\n  @@map("verification")\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"role","kind":"enum","type":"Role"},{"name":"isBanned","kind":"scalar","type":"Boolean"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"tutorProfile","kind":"object","type":"TutorProfile","relationName":"TutorProfileToUser"},{"name":"bookings","kind":"object","type":"Booking","relationName":"StudentBookings"},{"name":"reviews","kind":"object","type":"Review","relationName":"ReviewToUser"},{"name":"emailVerified","kind":"scalar","type":"Boolean"},{"name":"image","kind":"scalar","type":"String"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"sessions","kind":"object","type":"Session","relationName":"SessionToUser"},{"name":"accounts","kind":"object","type":"Account","relationName":"AccountToUser"},{"name":"phone","kind":"scalar","type":"String"},{"name":"status","kind":"scalar","type":"String"}],"dbName":"users"},"TutorProfile":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"bio","kind":"scalar","type":"String"},{"name":"image","kind":"scalar","type":"String"},{"name":"hourlyRate","kind":"scalar","type":"Float"},{"name":"rating","kind":"scalar","type":"Float"},{"name":"isApproved","kind":"scalar","type":"Boolean"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"user","kind":"object","type":"User","relationName":"TutorProfileToUser"},{"name":"categoryId","kind":"scalar","type":"String"},{"name":"category","kind":"object","type":"Category","relationName":"CategoryToTutorProfile"},{"name":"bookings","kind":"object","type":"Booking","relationName":"TutorBookings"},{"name":"reviews","kind":"object","type":"Review","relationName":"ReviewToTutorProfile"},{"name":"availability","kind":"object","type":"Availability","relationName":"AvailabilityToTutorProfile"}],"dbName":"tutor_profiles"},"Category":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"tutors","kind":"object","type":"TutorProfile","relationName":"CategoryToTutorProfile"}],"dbName":"categories"},"Availability":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"tutorId","kind":"scalar","type":"String"},{"name":"day","kind":"scalar","type":"String"},{"name":"startTime","kind":"scalar","type":"String"},{"name":"endTime","kind":"scalar","type":"String"},{"name":"tutor","kind":"object","type":"TutorProfile","relationName":"AvailabilityToTutorProfile"}],"dbName":"availability"},"Booking":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"studentId","kind":"scalar","type":"String"},{"name":"tutorId","kind":"scalar","type":"String"},{"name":"date","kind":"scalar","type":"String"},{"name":"time","kind":"scalar","type":"String"},{"name":"status","kind":"enum","type":"BookingStatus"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"student","kind":"object","type":"User","relationName":"StudentBookings"},{"name":"tutor","kind":"object","type":"TutorProfile","relationName":"TutorBookings"}],"dbName":"bookings"},"Review":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"tutorId","kind":"scalar","type":"String"},{"name":"rating","kind":"scalar","type":"Int"},{"name":"comment","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"user","kind":"object","type":"User","relationName":"ReviewToUser"},{"name":"tutor","kind":"object","type":"TutorProfile","relationName":"ReviewToTutorProfile"}],"dbName":"reviews"},"Session":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"token","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"ipAddress","kind":"scalar","type":"String"},{"name":"userAgent","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"SessionToUser"}],"dbName":"session"},"Account":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"accountId","kind":"scalar","type":"String"},{"name":"providerId","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"AccountToUser"},{"name":"accessToken","kind":"scalar","type":"String"},{"name":"refreshToken","kind":"scalar","type":"String"},{"name":"idToken","kind":"scalar","type":"String"},{"name":"accessTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"refreshTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"scope","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"account"},"Verification":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"identifier","kind":"scalar","type":"String"},{"name":"value","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"verification"}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","user","orderBy","cursor","tutors","_count","category","student","tutor","bookings","reviews","availability","tutorProfile","sessions","accounts","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","data","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","create","update","User.upsertOne","User.deleteOne","User.deleteMany","having","_min","_max","User.groupBy","User.aggregate","TutorProfile.findUnique","TutorProfile.findUniqueOrThrow","TutorProfile.findFirst","TutorProfile.findFirstOrThrow","TutorProfile.findMany","TutorProfile.createOne","TutorProfile.createMany","TutorProfile.createManyAndReturn","TutorProfile.updateOne","TutorProfile.updateMany","TutorProfile.updateManyAndReturn","TutorProfile.upsertOne","TutorProfile.deleteOne","TutorProfile.deleteMany","_avg","_sum","TutorProfile.groupBy","TutorProfile.aggregate","Category.findUnique","Category.findUniqueOrThrow","Category.findFirst","Category.findFirstOrThrow","Category.findMany","Category.createOne","Category.createMany","Category.createManyAndReturn","Category.updateOne","Category.updateMany","Category.updateManyAndReturn","Category.upsertOne","Category.deleteOne","Category.deleteMany","Category.groupBy","Category.aggregate","Availability.findUnique","Availability.findUniqueOrThrow","Availability.findFirst","Availability.findFirstOrThrow","Availability.findMany","Availability.createOne","Availability.createMany","Availability.createManyAndReturn","Availability.updateOne","Availability.updateMany","Availability.updateManyAndReturn","Availability.upsertOne","Availability.deleteOne","Availability.deleteMany","Availability.groupBy","Availability.aggregate","Booking.findUnique","Booking.findUniqueOrThrow","Booking.findFirst","Booking.findFirstOrThrow","Booking.findMany","Booking.createOne","Booking.createMany","Booking.createManyAndReturn","Booking.updateOne","Booking.updateMany","Booking.updateManyAndReturn","Booking.upsertOne","Booking.deleteOne","Booking.deleteMany","Booking.groupBy","Booking.aggregate","Review.findUnique","Review.findUniqueOrThrow","Review.findFirst","Review.findFirstOrThrow","Review.findMany","Review.createOne","Review.createMany","Review.createManyAndReturn","Review.updateOne","Review.updateMany","Review.updateManyAndReturn","Review.upsertOne","Review.deleteOne","Review.deleteMany","Review.groupBy","Review.aggregate","Session.findUnique","Session.findUniqueOrThrow","Session.findFirst","Session.findFirstOrThrow","Session.findMany","Session.createOne","Session.createMany","Session.createManyAndReturn","Session.updateOne","Session.updateMany","Session.updateManyAndReturn","Session.upsertOne","Session.deleteOne","Session.deleteMany","Session.groupBy","Session.aggregate","Account.findUnique","Account.findUniqueOrThrow","Account.findFirst","Account.findFirstOrThrow","Account.findMany","Account.createOne","Account.createMany","Account.createManyAndReturn","Account.updateOne","Account.updateMany","Account.updateManyAndReturn","Account.upsertOne","Account.deleteOne","Account.deleteMany","Account.groupBy","Account.aggregate","Verification.findUnique","Verification.findUniqueOrThrow","Verification.findFirst","Verification.findFirstOrThrow","Verification.findMany","Verification.createOne","Verification.createMany","Verification.createManyAndReturn","Verification.updateOne","Verification.updateMany","Verification.updateManyAndReturn","Verification.upsertOne","Verification.deleteOne","Verification.deleteMany","Verification.groupBy","Verification.aggregate","AND","OR","NOT","id","identifier","value","expiresAt","createdAt","updatedAt","equals","in","notIn","lt","lte","gt","gte","not","contains","startsWith","endsWith","accountId","providerId","userId","accessToken","refreshToken","idToken","accessTokenExpiresAt","refreshTokenExpiresAt","scope","password","token","ipAddress","userAgent","tutorId","rating","comment","studentId","date","time","BookingStatus","status","day","startTime","endTime","name","every","some","none","bio","image","hourlyRate","isApproved","categoryId","email","Role","role","isBanned","emailVerified","phone","userId_tutorId","is","isNot","connectOrCreate","upsert","createMany","set","disconnect","delete","connect","updateMany","deleteMany","increment","decrement","multiply","divide"]'),
  graph: "ngRQkAEUCQAAogIAIAoAAKMCACAMAAChAgAgDQAApAIAIA4AAKUCACCnAQAAnQIAMKgBAAAnABCpAQAAnQIAMKoBAQAAAAGuAUAA_QEAIa8BQAD9AQAhxAEBAJ4CACHPAQEAngIAIdMBAQD8AQAh2AEBAJ4CACHcAQEAAAAB3gEAAJ8C3gEi3wEgAKACACHgASAAoAIAIeEBAQCeAgAhAQAAAAEAIBEBAACoAgAgBgAAswIAIAkAAKICACAKAACjAgAgCwAAtAIAIKcBAACxAgAwqAEAAAMAEKkBAACxAgAwqgEBAPwBACGuAUAA_QEAIb0BAQD8AQAhyQEIALICACHXAQEAngIAIdgBAQCeAgAh2QEIALICACHaASAAoAIAIdsBAQD8AQAhAQAAAAMAIAcBAADnAwAgBgAA6AMAIAkAAOMDACAKAADkAwAgCwAA6QMAINcBAAC6AgAg2AEAALoCACARAQAAqAIAIAYAALMCACAJAACiAgAgCgAAowIAIAsAALQCACCnAQAAsQIAMKgBAAADABCpAQAAsQIAMKoBAQAAAAGuAUAA_QEAIb0BAQAAAAHJAQgAsgIAIdcBAQCeAgAh2AEBAJ4CACHZAQgAsgIAIdoBIACgAgAh2wEBAPwBACEDAAAAAwAgAgAABQAwAwAABgAgAQAAAAMAIAwHAACoAgAgCAAAqwIAIKcBAACvAgAwqAEAAAkAEKkBAACvAgAwqgEBAPwBACGuAUAA_QEAIcgBAQD8AQAhywEBAPwBACHMAQEA_AEAIc0BAQD8AQAhzwEAALACzwEiAgcAAOcDACAIAADiAwAgDAcAAKgCACAIAACrAgAgpwEAAK8CADCoAQAACQAQqQEAAK8CADCqAQEAAAABrgFAAP0BACHIAQEA_AEAIcsBAQD8AQAhzAEBAPwBACHNAQEA_AEAIc8BAACwAs8BIgMAAAAJACACAAAKADADAAALACALAQAAqAIAIAgAAKsCACCnAQAArQIAMKgBAAANABCpAQAArQIAMKoBAQD8AQAhrgFAAP0BACG9AQEA_AEAIcgBAQD8AQAhyQECAK4CACHKAQEA_AEAIQIBAADnAwAgCAAA4gMAIAwBAACoAgAgCAAAqwIAIKcBAACtAgAwqAEAAA0AEKkBAACtAgAwqgEBAAAAAa4BQAD9AQAhvQEBAPwBACHIAQEA_AEAIckBAgCuAgAhygEBAPwBACHiAQAArAIAIAMAAAANACACAAAOADADAAAPACAJCAAAqwIAIKcBAACqAgAwqAEAABEAEKkBAACqAgAwqgEBAPwBACHIAQEA_AEAIdABAQD8AQAh0QEBAPwBACHSAQEA_AEAIQEIAADiAwAgCQgAAKsCACCnAQAAqgIAMKgBAAARABCpAQAAqgIAMKoBAQAAAAHIAQEA_AEAIdABAQD8AQAh0QEBAPwBACHSAQEA_AEAIQMAAAARACACAAASADADAAATACABAAAACQAgAQAAAA0AIAEAAAARACADAAAACQAgAgAACgAwAwAACwAgAwAAAA0AIAIAAA4AMAMAAA8AIAwBAACoAgAgpwEAAKkCADCoAQAAGgAQqQEAAKkCADCqAQEA_AEAIa0BQAD9AQAhrgFAAP0BACGvAUAA_QEAIb0BAQD8AQAhxQEBAPwBACHGAQEAngIAIccBAQCeAgAhAwEAAOcDACDGAQAAugIAIMcBAAC6AgAgDAEAAKgCACCnAQAAqQIAMKgBAAAaABCpAQAAqQIAMKoBAQAAAAGtAUAA_QEAIa4BQAD9AQAhrwFAAP0BACG9AQEA_AEAIcUBAQAAAAHGAQEAngIAIccBAQCeAgAhAwAAABoAIAIAABsAMAMAABwAIBEBAACoAgAgpwEAAKYCADCoAQAAHgAQqQEAAKYCADCqAQEA_AEAIa4BQAD9AQAhrwFAAP0BACG7AQEA_AEAIbwBAQD8AQAhvQEBAPwBACG-AQEAngIAIb8BAQCeAgAhwAEBAJ4CACHBAUAApwIAIcIBQACnAgAhwwEBAJ4CACHEAQEAngIAIQgBAADnAwAgvgEAALoCACC_AQAAugIAIMABAAC6AgAgwQEAALoCACDCAQAAugIAIMMBAAC6AgAgxAEAALoCACARAQAAqAIAIKcBAACmAgAwqAEAAB4AEKkBAACmAgAwqgEBAAAAAa4BQAD9AQAhrwFAAP0BACG7AQEA_AEAIbwBAQD8AQAhvQEBAPwBACG-AQEAngIAIb8BAQCeAgAhwAEBAJ4CACHBAUAApwIAIcIBQACnAgAhwwEBAJ4CACHEAQEAngIAIQMAAAAeACACAAAfADADAAAgACABAAAACQAgAQAAAA0AIAEAAAAaACABAAAAHgAgAQAAAAEAIBQJAACiAgAgCgAAowIAIAwAAKECACANAACkAgAgDgAApQIAIKcBAACdAgAwqAEAACcAEKkBAACdAgAwqgEBAPwBACGuAUAA_QEAIa8BQAD9AQAhxAEBAJ4CACHPAQEAngIAIdMBAQD8AQAh2AEBAJ4CACHcAQEA_AEAId4BAACfAt4BIt8BIACgAgAh4AEgAKACACHhAQEAngIAIQkJAADjAwAgCgAA5AMAIAwAAOIDACANAADlAwAgDgAA5gMAIMQBAAC6AgAgzwEAALoCACDYAQAAugIAIOEBAAC6AgAgAwAAACcAIAIAACgAMAMAAAEAIAMAAAAnACACAAAoADADAAABACADAAAAJwAgAgAAKAAwAwAAAQAgEQkAAN4DACAKAADfAwAgDAAA3QMAIA0AAOADACAOAADhAwAgqgEBAAAAAa4BQAAAAAGvAUAAAAABxAEBAAAAAc8BAQAAAAHTAQEAAAAB2AEBAAAAAdwBAQAAAAHeAQAAAN4BAt8BIAAAAAHgASAAAAAB4QEBAAAAAQEUAAAsACAMqgEBAAAAAa4BQAAAAAGvAUAAAAABxAEBAAAAAc8BAQAAAAHTAQEAAAAB2AEBAAAAAdwBAQAAAAHeAQAAAN4BAt8BIAAAAAHgASAAAAAB4QEBAAAAAQEUAAAuADABFAAALgAwEQkAAKoDACAKAACrAwAgDAAAqQMAIA0AAKwDACAOAACtAwAgqgEBALgCACGuAUAAuQIAIa8BQAC5AgAhxAEBAL4CACHPAQEAvgIAIdMBAQC4AgAh2AEBAL4CACHcAQEAuAIAId4BAACoA94BIt8BIADtAgAh4AEgAO0CACHhAQEAvgIAIQIAAAABACAUAAAxACAMqgEBALgCACGuAUAAuQIAIa8BQAC5AgAhxAEBAL4CACHPAQEAvgIAIdMBAQC4AgAh2AEBAL4CACHcAQEAuAIAId4BAACoA94BIt8BIADtAgAh4AEgAO0CACHhAQEAvgIAIQIAAAAnACAUAAAzACACAAAAJwAgFAAAMwAgAwAAAAEAIBsAACwAIBwAADEAIAEAAAABACABAAAAJwAgBwUAAKUDACAhAACnAwAgIgAApgMAIMQBAAC6AgAgzwEAALoCACDYAQAAugIAIOEBAAC6AgAgD6cBAACZAgAwqAEAADoAEKkBAACZAgAwqgEBAPQBACGuAUAA9QEAIa8BQAD1AQAhxAEBAP8BACHPAQEA_wEAIdMBAQD0AQAh2AEBAP8BACHcAQEA9AEAId4BAACaAt4BIt8BIACVAgAh4AEgAJUCACHhAQEA_wEAIQMAAAAnACACAAA5ADAgAAA6ACADAAAAJwAgAgAAKAAwAwAAAQAgAQAAAAYAIAEAAAAGACADAAAAAwAgAgAABQAwAwAABgAgAwAAAAMAIAIAAAUAMAMAAAYAIAMAAAADACACAAAFADADAAAGACAOAQAAmAMAIAYAAKQDACAJAACZAwAgCgAAmgMAIAsAAJsDACCqAQEAAAABrgFAAAAAAb0BAQAAAAHJAQgAAAAB1wEBAAAAAdgBAQAAAAHZAQgAAAAB2gEgAAAAAdsBAQAAAAEBFAAAQgAgCaoBAQAAAAGuAUAAAAABvQEBAAAAAckBCAAAAAHXAQEAAAAB2AEBAAAAAdkBCAAAAAHaASAAAAAB2wEBAAAAAQEUAABEADABFAAARAAwDgEAAO8CACAGAACjAwAgCQAA8AIAIAoAAPECACALAADyAgAgqgEBALgCACGuAUAAuQIAIb0BAQC4AgAhyQEIAOwCACHXAQEAvgIAIdgBAQC-AgAh2QEIAOwCACHaASAA7QIAIdsBAQC4AgAhAgAAAAYAIBQAAEcAIAmqAQEAuAIAIa4BQAC5AgAhvQEBALgCACHJAQgA7AIAIdcBAQC-AgAh2AEBAL4CACHZAQgA7AIAIdoBIADtAgAh2wEBALgCACECAAAAAwAgFAAASQAgAgAAAAMAIBQAAEkAIAMAAAAGACAbAABCACAcAABHACABAAAABgAgAQAAAAMAIAcFAACeAwAgIQAAoQMAICIAAKADACAzAACfAwAgNAAAogMAINcBAAC6AgAg2AEAALoCACAMpwEAAJMCADCoAQAAUAAQqQEAAJMCADCqAQEA9AEAIa4BQAD1AQAhvQEBAPQBACHJAQgAlAIAIdcBAQD_AQAh2AEBAP8BACHZAQgAlAIAIdoBIACVAgAh2wEBAPQBACEDAAAAAwAgAgAATwAwIAAAUAAgAwAAAAMAIAIAAAUAMAMAAAYAIAYEAACSAgAgpwEAAJECADCoAQAAVgAQqQEAAJECADCqAQEAAAAB0wEBAAAAAQEAAABTACABAAAAUwAgBgQAAJICACCnAQAAkQIAMKgBAABWABCpAQAAkQIAMKoBAQD8AQAh0wEBAPwBACEBBAAAnQMAIAMAAABWACACAABXADADAABTACADAAAAVgAgAgAAVwAwAwAAUwAgAwAAAFYAIAIAAFcAMAMAAFMAIAMEAACcAwAgqgEBAAAAAdMBAQAAAAEBFAAAWwAgAqoBAQAAAAHTAQEAAAABARQAAF0AMAEUAABdADADBAAA4QIAIKoBAQC4AgAh0wEBALgCACECAAAAUwAgFAAAYAAgAqoBAQC4AgAh0wEBALgCACECAAAAVgAgFAAAYgAgAgAAAFYAIBQAAGIAIAMAAABTACAbAABbACAcAABgACABAAAAUwAgAQAAAFYAIAMFAADeAgAgIQAA4AIAICIAAN8CACAFpwEAAJACADCoAQAAaQAQqQEAAJACADCqAQEA9AEAIdMBAQD0AQAhAwAAAFYAIAIAAGgAMCAAAGkAIAMAAABWACACAABXADADAABTACABAAAAEwAgAQAAABMAIAMAAAARACACAAASADADAAATACADAAAAEQAgAgAAEgAwAwAAEwAgAwAAABEAIAIAABIAMAMAABMAIAYIAADdAgAgqgEBAAAAAcgBAQAAAAHQAQEAAAAB0QEBAAAAAdIBAQAAAAEBFAAAcQAgBaoBAQAAAAHIAQEAAAAB0AEBAAAAAdEBAQAAAAHSAQEAAAABARQAAHMAMAEUAABzADAGCAAA3AIAIKoBAQC4AgAhyAEBALgCACHQAQEAuAIAIdEBAQC4AgAh0gEBALgCACECAAAAEwAgFAAAdgAgBaoBAQC4AgAhyAEBALgCACHQAQEAuAIAIdEBAQC4AgAh0gEBALgCACECAAAAEQAgFAAAeAAgAgAAABEAIBQAAHgAIAMAAAATACAbAABxACAcAAB2ACABAAAAEwAgAQAAABEAIAMFAADZAgAgIQAA2wIAICIAANoCACAIpwEAAI8CADCoAQAAfwAQqQEAAI8CADCqAQEA9AEAIcgBAQD0AQAh0AEBAPQBACHRAQEA9AEAIdIBAQD0AQAhAwAAABEAIAIAAH4AMCAAAH8AIAMAAAARACACAAASADADAAATACABAAAACwAgAQAAAAsAIAMAAAAJACACAAAKADADAAALACADAAAACQAgAgAACgAwAwAACwAgAwAAAAkAIAIAAAoAMAMAAAsAIAkHAADXAgAgCAAA2AIAIKoBAQAAAAGuAUAAAAAByAEBAAAAAcsBAQAAAAHMAQEAAAABzQEBAAAAAc8BAAAAzwECARQAAIcBACAHqgEBAAAAAa4BQAAAAAHIAQEAAAABywEBAAAAAcwBAQAAAAHNAQEAAAABzwEAAADPAQIBFAAAiQEAMAEUAACJAQAwCQcAANUCACAIAADWAgAgqgEBALgCACGuAUAAuQIAIcgBAQC4AgAhywEBALgCACHMAQEAuAIAIc0BAQC4AgAhzwEAANQCzwEiAgAAAAsAIBQAAIwBACAHqgEBALgCACGuAUAAuQIAIcgBAQC4AgAhywEBALgCACHMAQEAuAIAIc0BAQC4AgAhzwEAANQCzwEiAgAAAAkAIBQAAI4BACACAAAACQAgFAAAjgEAIAMAAAALACAbAACHAQAgHAAAjAEAIAEAAAALACABAAAACQAgAwUAANECACAhAADTAgAgIgAA0gIAIAqnAQAAiwIAMKgBAACVAQAQqQEAAIsCADCqAQEA9AEAIa4BQAD1AQAhyAEBAPQBACHLAQEA9AEAIcwBAQD0AQAhzQEBAPQBACHPAQAAjALPASIDAAAACQAgAgAAlAEAMCAAAJUBACADAAAACQAgAgAACgAwAwAACwAgAQAAAA8AIAEAAAAPACADAAAADQAgAgAADgAwAwAADwAgAwAAAA0AIAIAAA4AMAMAAA8AIAMAAAANACACAAAOADADAAAPACAIAQAAzwIAIAgAANACACCqAQEAAAABrgFAAAAAAb0BAQAAAAHIAQEAAAAByQECAAAAAcoBAQAAAAEBFAAAnQEAIAaqAQEAAAABrgFAAAAAAb0BAQAAAAHIAQEAAAAByQECAAAAAcoBAQAAAAEBFAAAnwEAMAEUAACfAQAwCAEAAM0CACAIAADOAgAgqgEBALgCACGuAUAAuQIAIb0BAQC4AgAhyAEBALgCACHJAQIAzAIAIcoBAQC4AgAhAgAAAA8AIBQAAKIBACAGqgEBALgCACGuAUAAuQIAIb0BAQC4AgAhyAEBALgCACHJAQIAzAIAIcoBAQC4AgAhAgAAAA0AIBQAAKQBACACAAAADQAgFAAApAEAIAMAAAAPACAbAACdAQAgHAAAogEAIAEAAAAPACABAAAADQAgBQUAAMcCACAhAADKAgAgIgAAyQIAIDMAAMgCACA0AADLAgAgCacBAACHAgAwqAEAAKsBABCpAQAAhwIAMKoBAQD0AQAhrgFAAPUBACG9AQEA9AEAIcgBAQD0AQAhyQECAIgCACHKAQEA9AEAIQMAAAANACACAACqAQAwIAAAqwEAIAMAAAANACACAAAOADADAAAPACABAAAAHAAgAQAAABwAIAMAAAAaACACAAAbADADAAAcACADAAAAGgAgAgAAGwAwAwAAHAAgAwAAABoAIAIAABsAMAMAABwAIAkBAADGAgAgqgEBAAAAAa0BQAAAAAGuAUAAAAABrwFAAAAAAb0BAQAAAAHFAQEAAAABxgEBAAAAAccBAQAAAAEBFAAAswEAIAiqAQEAAAABrQFAAAAAAa4BQAAAAAGvAUAAAAABvQEBAAAAAcUBAQAAAAHGAQEAAAABxwEBAAAAAQEUAAC1AQAwARQAALUBADAJAQAAxQIAIKoBAQC4AgAhrQFAALkCACGuAUAAuQIAIa8BQAC5AgAhvQEBALgCACHFAQEAuAIAIcYBAQC-AgAhxwEBAL4CACECAAAAHAAgFAAAuAEAIAiqAQEAuAIAIa0BQAC5AgAhrgFAALkCACGvAUAAuQIAIb0BAQC4AgAhxQEBALgCACHGAQEAvgIAIccBAQC-AgAhAgAAABoAIBQAALoBACACAAAAGgAgFAAAugEAIAMAAAAcACAbAACzAQAgHAAAuAEAIAEAAAAcACABAAAAGgAgBQUAAMICACAhAADEAgAgIgAAwwIAIMYBAAC6AgAgxwEAALoCACALpwEAAIYCADCoAQAAwQEAEKkBAACGAgAwqgEBAPQBACGtAUAA9QEAIa4BQAD1AQAhrwFAAPUBACG9AQEA9AEAIcUBAQD0AQAhxgEBAP8BACHHAQEA_wEAIQMAAAAaACACAADAAQAwIAAAwQEAIAMAAAAaACACAAAbADADAAAcACABAAAAIAAgAQAAACAAIAMAAAAeACACAAAfADADAAAgACADAAAAHgAgAgAAHwAwAwAAIAAgAwAAAB4AIAIAAB8AMAMAACAAIA4BAADBAgAgqgEBAAAAAa4BQAAAAAGvAUAAAAABuwEBAAAAAbwBAQAAAAG9AQEAAAABvgEBAAAAAb8BAQAAAAHAAQEAAAABwQFAAAAAAcIBQAAAAAHDAQEAAAABxAEBAAAAAQEUAADJAQAgDaoBAQAAAAGuAUAAAAABrwFAAAAAAbsBAQAAAAG8AQEAAAABvQEBAAAAAb4BAQAAAAG_AQEAAAABwAEBAAAAAcEBQAAAAAHCAUAAAAABwwEBAAAAAcQBAQAAAAEBFAAAywEAMAEUAADLAQAwDgEAAMACACCqAQEAuAIAIa4BQAC5AgAhrwFAALkCACG7AQEAuAIAIbwBAQC4AgAhvQEBALgCACG-AQEAvgIAIb8BAQC-AgAhwAEBAL4CACHBAUAAvwIAIcIBQAC_AgAhwwEBAL4CACHEAQEAvgIAIQIAAAAgACAUAADOAQAgDaoBAQC4AgAhrgFAALkCACGvAUAAuQIAIbsBAQC4AgAhvAEBALgCACG9AQEAuAIAIb4BAQC-AgAhvwEBAL4CACHAAQEAvgIAIcEBQAC_AgAhwgFAAL8CACHDAQEAvgIAIcQBAQC-AgAhAgAAAB4AIBQAANABACACAAAAHgAgFAAA0AEAIAMAAAAgACAbAADJAQAgHAAAzgEAIAEAAAAgACABAAAAHgAgCgUAALsCACAhAAC9AgAgIgAAvAIAIL4BAAC6AgAgvwEAALoCACDAAQAAugIAIMEBAAC6AgAgwgEAALoCACDDAQAAugIAIMQBAAC6AgAgEKcBAAD-AQAwqAEAANcBABCpAQAA_gEAMKoBAQD0AQAhrgFAAPUBACGvAUAA9QEAIbsBAQD0AQAhvAEBAPQBACG9AQEA9AEAIb4BAQD_AQAhvwEBAP8BACHAAQEA_wEAIcEBQACAAgAhwgFAAIACACHDAQEA_wEAIcQBAQD_AQAhAwAAAB4AIAIAANYBADAgAADXAQAgAwAAAB4AIAIAAB8AMAMAACAAIAmnAQAA-wEAMKgBAADdAQAQqQEAAPsBADCqAQEAAAABqwEBAPwBACGsAQEA_AEAIa0BQAD9AQAhrgFAAP0BACGvAUAA_QEAIQEAAADaAQAgAQAAANoBACAJpwEAAPsBADCoAQAA3QEAEKkBAAD7AQAwqgEBAPwBACGrAQEA_AEAIawBAQD8AQAhrQFAAP0BACGuAUAA_QEAIa8BQAD9AQAhAAMAAADdAQAgAgAA3gEAMAMAANoBACADAAAA3QEAIAIAAN4BADADAADaAQAgAwAAAN0BACACAADeAQAwAwAA2gEAIAaqAQEAAAABqwEBAAAAAawBAQAAAAGtAUAAAAABrgFAAAAAAa8BQAAAAAEBFAAA4gEAIAaqAQEAAAABqwEBAAAAAawBAQAAAAGtAUAAAAABrgFAAAAAAa8BQAAAAAEBFAAA5AEAMAEUAADkAQAwBqoBAQC4AgAhqwEBALgCACGsAQEAuAIAIa0BQAC5AgAhrgFAALkCACGvAUAAuQIAIQIAAADaAQAgFAAA5wEAIAaqAQEAuAIAIasBAQC4AgAhrAEBALgCACGtAUAAuQIAIa4BQAC5AgAhrwFAALkCACECAAAA3QEAIBQAAOkBACACAAAA3QEAIBQAAOkBACADAAAA2gEAIBsAAOIBACAcAADnAQAgAQAAANoBACABAAAA3QEAIAMFAAC1AgAgIQAAtwIAICIAALYCACAJpwEAAPMBADCoAQAA8AEAEKkBAADzAQAwqgEBAPQBACGrAQEA9AEAIawBAQD0AQAhrQFAAPUBACGuAUAA9QEAIa8BQAD1AQAhAwAAAN0BACACAADvAQAwIAAA8AEAIAMAAADdAQAgAgAA3gEAMAMAANoBACAJpwEAAPMBADCoAQAA8AEAEKkBAADzAQAwqgEBAPQBACGrAQEA9AEAIawBAQD0AQAhrQFAAPUBACGuAUAA9QEAIa8BQAD1AQAhDgUAAPcBACAhAAD6AQAgIgAA-gEAILABAQAAAAGxAQEAAAAEsgEBAAAABLMBAQAAAAG0AQEAAAABtQEBAAAAAbYBAQAAAAG3AQEA-QEAIbgBAQAAAAG5AQEAAAABugEBAAAAAQsFAAD3AQAgIQAA-AEAICIAAPgBACCwAUAAAAABsQFAAAAABLIBQAAAAASzAUAAAAABtAFAAAAAAbUBQAAAAAG2AUAAAAABtwFAAPYBACELBQAA9wEAICEAAPgBACAiAAD4AQAgsAFAAAAAAbEBQAAAAASyAUAAAAAEswFAAAAAAbQBQAAAAAG1AUAAAAABtgFAAAAAAbcBQAD2AQAhCLABAgAAAAGxAQIAAAAEsgECAAAABLMBAgAAAAG0AQIAAAABtQECAAAAAbYBAgAAAAG3AQIA9wEAIQiwAUAAAAABsQFAAAAABLIBQAAAAASzAUAAAAABtAFAAAAAAbUBQAAAAAG2AUAAAAABtwFAAPgBACEOBQAA9wEAICEAAPoBACAiAAD6AQAgsAEBAAAAAbEBAQAAAASyAQEAAAAEswEBAAAAAbQBAQAAAAG1AQEAAAABtgEBAAAAAbcBAQD5AQAhuAEBAAAAAbkBAQAAAAG6AQEAAAABC7ABAQAAAAGxAQEAAAAEsgEBAAAABLMBAQAAAAG0AQEAAAABtQEBAAAAAbYBAQAAAAG3AQEA-gEAIbgBAQAAAAG5AQEAAAABugEBAAAAAQmnAQAA-wEAMKgBAADdAQAQqQEAAPsBADCqAQEA_AEAIasBAQD8AQAhrAEBAPwBACGtAUAA_QEAIa4BQAD9AQAhrwFAAP0BACELsAEBAAAAAbEBAQAAAASyAQEAAAAEswEBAAAAAbQBAQAAAAG1AQEAAAABtgEBAAAAAbcBAQD6AQAhuAEBAAAAAbkBAQAAAAG6AQEAAAABCLABQAAAAAGxAUAAAAAEsgFAAAAABLMBQAAAAAG0AUAAAAABtQFAAAAAAbYBQAAAAAG3AUAA-AEAIRCnAQAA_gEAMKgBAADXAQAQqQEAAP4BADCqAQEA9AEAIa4BQAD1AQAhrwFAAPUBACG7AQEA9AEAIbwBAQD0AQAhvQEBAPQBACG-AQEA_wEAIb8BAQD_AQAhwAEBAP8BACHBAUAAgAIAIcIBQACAAgAhwwEBAP8BACHEAQEA_wEAIQ4FAACCAgAgIQAAhQIAICIAAIUCACCwAQEAAAABsQEBAAAABbIBAQAAAAWzAQEAAAABtAEBAAAAAbUBAQAAAAG2AQEAAAABtwEBAIQCACG4AQEAAAABuQEBAAAAAboBAQAAAAELBQAAggIAICEAAIMCACAiAACDAgAgsAFAAAAAAbEBQAAAAAWyAUAAAAAFswFAAAAAAbQBQAAAAAG1AUAAAAABtgFAAAAAAbcBQACBAgAhCwUAAIICACAhAACDAgAgIgAAgwIAILABQAAAAAGxAUAAAAAFsgFAAAAABbMBQAAAAAG0AUAAAAABtQFAAAAAAbYBQAAAAAG3AUAAgQIAIQiwAQIAAAABsQECAAAABbIBAgAAAAWzAQIAAAABtAECAAAAAbUBAgAAAAG2AQIAAAABtwECAIICACEIsAFAAAAAAbEBQAAAAAWyAUAAAAAFswFAAAAAAbQBQAAAAAG1AUAAAAABtgFAAAAAAbcBQACDAgAhDgUAAIICACAhAACFAgAgIgAAhQIAILABAQAAAAGxAQEAAAAFsgEBAAAABbMBAQAAAAG0AQEAAAABtQEBAAAAAbYBAQAAAAG3AQEAhAIAIbgBAQAAAAG5AQEAAAABugEBAAAAAQuwAQEAAAABsQEBAAAABbIBAQAAAAWzAQEAAAABtAEBAAAAAbUBAQAAAAG2AQEAAAABtwEBAIUCACG4AQEAAAABuQEBAAAAAboBAQAAAAELpwEAAIYCADCoAQAAwQEAEKkBAACGAgAwqgEBAPQBACGtAUAA9QEAIa4BQAD1AQAhrwFAAPUBACG9AQEA9AEAIcUBAQD0AQAhxgEBAP8BACHHAQEA_wEAIQmnAQAAhwIAMKgBAACrAQAQqQEAAIcCADCqAQEA9AEAIa4BQAD1AQAhvQEBAPQBACHIAQEA9AEAIckBAgCIAgAhygEBAPQBACENBQAA9wEAICEAAPcBACAiAAD3AQAgMwAAigIAIDQAAPcBACCwAQIAAAABsQECAAAABLIBAgAAAASzAQIAAAABtAECAAAAAbUBAgAAAAG2AQIAAAABtwECAIkCACENBQAA9wEAICEAAPcBACAiAAD3AQAgMwAAigIAIDQAAPcBACCwAQIAAAABsQECAAAABLIBAgAAAASzAQIAAAABtAECAAAAAbUBAgAAAAG2AQIAAAABtwECAIkCACEIsAEIAAAAAbEBCAAAAASyAQgAAAAEswEIAAAAAbQBCAAAAAG1AQgAAAABtgEIAAAAAbcBCACKAgAhCqcBAACLAgAwqAEAAJUBABCpAQAAiwIAMKoBAQD0AQAhrgFAAPUBACHIAQEA9AEAIcsBAQD0AQAhzAEBAPQBACHNAQEA9AEAIc8BAACMAs8BIgcFAAD3AQAgIQAAjgIAICIAAI4CACCwAQAAAM8BArEBAAAAzwEIsgEAAADPAQi3AQAAjQLPASIHBQAA9wEAICEAAI4CACAiAACOAgAgsAEAAADPAQKxAQAAAM8BCLIBAAAAzwEItwEAAI0CzwEiBLABAAAAzwECsQEAAADPAQiyAQAAAM8BCLcBAACOAs8BIginAQAAjwIAMKgBAAB_ABCpAQAAjwIAMKoBAQD0AQAhyAEBAPQBACHQAQEA9AEAIdEBAQD0AQAh0gEBAPQBACEFpwEAAJACADCoAQAAaQAQqQEAAJACADCqAQEA9AEAIdMBAQD0AQAhBgQAAJICACCnAQAAkQIAMKgBAABWABCpAQAAkQIAMKoBAQD8AQAh0wEBAPwBACED1AEAAAMAINUBAAADACDWAQAAAwAgDKcBAACTAgAwqAEAAFAAEKkBAACTAgAwqgEBAPQBACGuAUAA9QEAIb0BAQD0AQAhyQEIAJQCACHXAQEA_wEAIdgBAQD_AQAh2QEIAJQCACHaASAAlQIAIdsBAQD0AQAhDQUAAPcBACAhAACKAgAgIgAAigIAIDMAAIoCACA0AACKAgAgsAEIAAAAAbEBCAAAAASyAQgAAAAEswEIAAAAAbQBCAAAAAG1AQgAAAABtgEIAAAAAbcBCACYAgAhBQUAAPcBACAhAACXAgAgIgAAlwIAILABIAAAAAG3ASAAlgIAIQUFAAD3AQAgIQAAlwIAICIAAJcCACCwASAAAAABtwEgAJYCACECsAEgAAAAAbcBIACXAgAhDQUAAPcBACAhAACKAgAgIgAAigIAIDMAAIoCACA0AACKAgAgsAEIAAAAAbEBCAAAAASyAQgAAAAEswEIAAAAAbQBCAAAAAG1AQgAAAABtgEIAAAAAbcBCACYAgAhD6cBAACZAgAwqAEAADoAEKkBAACZAgAwqgEBAPQBACGuAUAA9QEAIa8BQAD1AQAhxAEBAP8BACHPAQEA_wEAIdMBAQD0AQAh2AEBAP8BACHcAQEA9AEAId4BAACaAt4BIt8BIACVAgAh4AEgAJUCACHhAQEA_wEAIQcFAAD3AQAgIQAAnAIAICIAAJwCACCwAQAAAN4BArEBAAAA3gEIsgEAAADeAQi3AQAAmwLeASIHBQAA9wEAICEAAJwCACAiAACcAgAgsAEAAADeAQKxAQAAAN4BCLIBAAAA3gEItwEAAJsC3gEiBLABAAAA3gECsQEAAADeAQiyAQAAAN4BCLcBAACcAt4BIhQJAACiAgAgCgAAowIAIAwAAKECACANAACkAgAgDgAApQIAIKcBAACdAgAwqAEAACcAEKkBAACdAgAwqgEBAPwBACGuAUAA_QEAIa8BQAD9AQAhxAEBAJ4CACHPAQEAngIAIdMBAQD8AQAh2AEBAJ4CACHcAQEA_AEAId4BAACfAt4BIt8BIACgAgAh4AEgAKACACHhAQEAngIAIQuwAQEAAAABsQEBAAAABbIBAQAAAAWzAQEAAAABtAEBAAAAAbUBAQAAAAG2AQEAAAABtwEBAIUCACG4AQEAAAABuQEBAAAAAboBAQAAAAEEsAEAAADeAQKxAQAAAN4BCLIBAAAA3gEItwEAAJwC3gEiArABIAAAAAG3ASAAlwIAIRMBAACoAgAgBgAAswIAIAkAAKICACAKAACjAgAgCwAAtAIAIKcBAACxAgAwqAEAAAMAEKkBAACxAgAwqgEBAPwBACGuAUAA_QEAIb0BAQD8AQAhyQEIALICACHXAQEAngIAIdgBAQCeAgAh2QEIALICACHaASAAoAIAIdsBAQD8AQAh4wEAAAMAIOQBAAADACAD1AEAAAkAINUBAAAJACDWAQAACQAgA9QBAAANACDVAQAADQAg1gEAAA0AIAPUAQAAGgAg1QEAABoAINYBAAAaACAD1AEAAB4AINUBAAAeACDWAQAAHgAgEQEAAKgCACCnAQAApgIAMKgBAAAeABCpAQAApgIAMKoBAQD8AQAhrgFAAP0BACGvAUAA_QEAIbsBAQD8AQAhvAEBAPwBACG9AQEA_AEAIb4BAQCeAgAhvwEBAJ4CACHAAQEAngIAIcEBQACnAgAhwgFAAKcCACHDAQEAngIAIcQBAQCeAgAhCLABQAAAAAGxAUAAAAAFsgFAAAAABbMBQAAAAAG0AUAAAAABtQFAAAAAAbYBQAAAAAG3AUAAgwIAIRYJAACiAgAgCgAAowIAIAwAAKECACANAACkAgAgDgAApQIAIKcBAACdAgAwqAEAACcAEKkBAACdAgAwqgEBAPwBACGuAUAA_QEAIa8BQAD9AQAhxAEBAJ4CACHPAQEAngIAIdMBAQD8AQAh2AEBAJ4CACHcAQEA_AEAId4BAACfAt4BIt8BIACgAgAh4AEgAKACACHhAQEAngIAIeMBAAAnACDkAQAAJwAgDAEAAKgCACCnAQAAqQIAMKgBAAAaABCpAQAAqQIAMKoBAQD8AQAhrQFAAP0BACGuAUAA_QEAIa8BQAD9AQAhvQEBAPwBACHFAQEA_AEAIcYBAQCeAgAhxwEBAJ4CACEJCAAAqwIAIKcBAACqAgAwqAEAABEAEKkBAACqAgAwqgEBAPwBACHIAQEA_AEAIdABAQD8AQAh0QEBAPwBACHSAQEA_AEAIRMBAACoAgAgBgAAswIAIAkAAKICACAKAACjAgAgCwAAtAIAIKcBAACxAgAwqAEAAAMAEKkBAACxAgAwqgEBAPwBACGuAUAA_QEAIb0BAQD8AQAhyQEIALICACHXAQEAngIAIdgBAQCeAgAh2QEIALICACHaASAAoAIAIdsBAQD8AQAh4wEAAAMAIOQBAAADACACvQEBAAAAAcgBAQAAAAELAQAAqAIAIAgAAKsCACCnAQAArQIAMKgBAAANABCpAQAArQIAMKoBAQD8AQAhrgFAAP0BACG9AQEA_AEAIcgBAQD8AQAhyQECAK4CACHKAQEA_AEAIQiwAQIAAAABsQECAAAABLIBAgAAAASzAQIAAAABtAECAAAAAbUBAgAAAAG2AQIAAAABtwECAPcBACEMBwAAqAIAIAgAAKsCACCnAQAArwIAMKgBAAAJABCpAQAArwIAMKoBAQD8AQAhrgFAAP0BACHIAQEA_AEAIcsBAQD8AQAhzAEBAPwBACHNAQEA_AEAIc8BAACwAs8BIgSwAQAAAM8BArEBAAAAzwEIsgEAAADPAQi3AQAAjgLPASIRAQAAqAIAIAYAALMCACAJAACiAgAgCgAAowIAIAsAALQCACCnAQAAsQIAMKgBAAADABCpAQAAsQIAMKoBAQD8AQAhrgFAAP0BACG9AQEA_AEAIckBCACyAgAh1wEBAJ4CACHYAQEAngIAIdkBCACyAgAh2gEgAKACACHbAQEA_AEAIQiwAQgAAAABsQEIAAAABLIBCAAAAASzAQgAAAABtAEIAAAAAbUBCAAAAAG2AQgAAAABtwEIAIoCACEIBAAAkgIAIKcBAACRAgAwqAEAAFYAEKkBAACRAgAwqgEBAPwBACHTAQEA_AEAIeMBAABWACDkAQAAVgAgA9QBAAARACDVAQAAEQAg1gEAABEAIAAAAAHoAQEAAAABAegBQAAAAAEAAAAAAegBAQAAAAEB6AFAAAAAAQUbAACaBAAgHAAAnQQAIOUBAACbBAAg5gEAAJwEACDrAQAAAQAgAxsAAJoEACDlAQAAmwQAIOsBAAABACAAAAAFGwAAlQQAIBwAAJgEACDlAQAAlgQAIOYBAACXBAAg6wEAAAEAIAMbAACVBAAg5QEAAJYEACDrAQAAAQAgAAAAAAAF6AECAAAAAe4BAgAAAAHvAQIAAAAB8AECAAAAAfEBAgAAAAEFGwAAjQQAIBwAAJMEACDlAQAAjgQAIOYBAACSBAAg6wEAAAEAIAUbAACLBAAgHAAAkAQAIOUBAACMBAAg5gEAAI8EACDrAQAABgAgAxsAAI0EACDlAQAAjgQAIOsBAAABACADGwAAiwQAIOUBAACMBAAg6wEAAAYAIAAAAAHoAQAAAM8BAgUbAACDBAAgHAAAiQQAIOUBAACEBAAg5gEAAIgEACDrAQAAAQAgBRsAAIEEACAcAACGBAAg5QEAAIIEACDmAQAAhQQAIOsBAAAGACADGwAAgwQAIOUBAACEBAAg6wEAAAEAIAMbAACBBAAg5QEAAIIEACDrAQAABgAgAAAABRsAAPwDACAcAAD_AwAg5QEAAP0DACDmAQAA_gMAIOsBAAAGACADGwAA_AMAIOUBAAD9AwAg6wEAAAYAIAAAAAsbAADiAgAwHAAA5wIAMOUBAADjAgAw5gEAAOQCADDnAQAA5QIAIOgBAADmAgAw6QEAAOYCADDqAQAA5gIAMOsBAADmAgAw7AEAAOgCADDtAQAA6QIAMAwBAACYAwAgCQAAmQMAIAoAAJoDACALAACbAwAgqgEBAAAAAa4BQAAAAAG9AQEAAAAByQEIAAAAAdcBAQAAAAHYAQEAAAAB2QEIAAAAAdoBIAAAAAECAAAABgAgGwAAlwMAIAMAAAAGACAbAACXAwAgHAAA7gIAIAEUAAD7AwAwEQEAAKgCACAGAACzAgAgCQAAogIAIAoAAKMCACALAAC0AgAgpwEAALECADCoAQAAAwAQqQEAALECADCqAQEAAAABrgFAAP0BACG9AQEAAAAByQEIALICACHXAQEAngIAIdgBAQCeAgAh2QEIALICACHaASAAoAIAIdsBAQD8AQAhAgAAAAYAIBQAAO4CACACAAAA6gIAIBQAAOsCACAMpwEAAOkCADCoAQAA6gIAEKkBAADpAgAwqgEBAPwBACGuAUAA_QEAIb0BAQD8AQAhyQEIALICACHXAQEAngIAIdgBAQCeAgAh2QEIALICACHaASAAoAIAIdsBAQD8AQAhDKcBAADpAgAwqAEAAOoCABCpAQAA6QIAMKoBAQD8AQAhrgFAAP0BACG9AQEA_AEAIckBCACyAgAh1wEBAJ4CACHYAQEAngIAIdkBCACyAgAh2gEgAKACACHbAQEA_AEAIQiqAQEAuAIAIa4BQAC5AgAhvQEBALgCACHJAQgA7AIAIdcBAQC-AgAh2AEBAL4CACHZAQgA7AIAIdoBIADtAgAhBegBCAAAAAHuAQgAAAAB7wEIAAAAAfABCAAAAAHxAQgAAAABAegBIAAAAAEMAQAA7wIAIAkAAPACACAKAADxAgAgCwAA8gIAIKoBAQC4AgAhrgFAALkCACG9AQEAuAIAIckBCADsAgAh1wEBAL4CACHYAQEAvgIAIdkBCADsAgAh2gEgAO0CACEFGwAA8wMAIBwAAPkDACDlAQAA9AMAIOYBAAD4AwAg6wEAAAEAIAsbAACLAwAwHAAAkAMAMOUBAACMAwAw5gEAAI0DADDnAQAAjgMAIOgBAACPAwAw6QEAAI8DADDqAQAAjwMAMOsBAACPAwAw7AEAAJEDADDtAQAAkgMAMAsbAAD_AgAwHAAAhAMAMOUBAACAAwAw5gEAAIEDADDnAQAAggMAIOgBAACDAwAw6QEAAIMDADDqAQAAgwMAMOsBAACDAwAw7AEAAIUDADDtAQAAhgMAMAsbAADzAgAwHAAA-AIAMOUBAAD0AgAw5gEAAPUCADDnAQAA9gIAIOgBAAD3AgAw6QEAAPcCADDqAQAA9wIAMOsBAAD3AgAw7AEAAPkCADDtAQAA-gIAMASqAQEAAAAB0AEBAAAAAdEBAQAAAAHSAQEAAAABAgAAABMAIBsAAP4CACADAAAAEwAgGwAA_gIAIBwAAP0CACABFAAA9wMAMAkIAACrAgAgpwEAAKoCADCoAQAAEQAQqQEAAKoCADCqAQEAAAAByAEBAPwBACHQAQEA_AEAIdEBAQD8AQAh0gEBAPwBACECAAAAEwAgFAAA_QIAIAIAAAD7AgAgFAAA_AIAIAinAQAA-gIAMKgBAAD7AgAQqQEAAPoCADCqAQEA_AEAIcgBAQD8AQAh0AEBAPwBACHRAQEA_AEAIdIBAQD8AQAhCKcBAAD6AgAwqAEAAPsCABCpAQAA-gIAMKoBAQD8AQAhyAEBAPwBACHQAQEA_AEAIdEBAQD8AQAh0gEBAPwBACEEqgEBALgCACHQAQEAuAIAIdEBAQC4AgAh0gEBALgCACEEqgEBALgCACHQAQEAuAIAIdEBAQC4AgAh0gEBALgCACEEqgEBAAAAAdABAQAAAAHRAQEAAAAB0gEBAAAAAQYBAADPAgAgqgEBAAAAAa4BQAAAAAG9AQEAAAAByQECAAAAAcoBAQAAAAECAAAADwAgGwAAigMAIAMAAAAPACAbAACKAwAgHAAAiQMAIAEUAAD2AwAwDAEAAKgCACAIAACrAgAgpwEAAK0CADCoAQAADQAQqQEAAK0CADCqAQEAAAABrgFAAP0BACG9AQEA_AEAIcgBAQD8AQAhyQECAK4CACHKAQEA_AEAIeIBAACsAgAgAgAAAA8AIBQAAIkDACACAAAAhwMAIBQAAIgDACAJpwEAAIYDADCoAQAAhwMAEKkBAACGAwAwqgEBAPwBACGuAUAA_QEAIb0BAQD8AQAhyAEBAPwBACHJAQIArgIAIcoBAQD8AQAhCacBAACGAwAwqAEAAIcDABCpAQAAhgMAMKoBAQD8AQAhrgFAAP0BACG9AQEA_AEAIcgBAQD8AQAhyQECAK4CACHKAQEA_AEAIQWqAQEAuAIAIa4BQAC5AgAhvQEBALgCACHJAQIAzAIAIcoBAQC4AgAhBgEAAM0CACCqAQEAuAIAIa4BQAC5AgAhvQEBALgCACHJAQIAzAIAIcoBAQC4AgAhBgEAAM8CACCqAQEAAAABrgFAAAAAAb0BAQAAAAHJAQIAAAABygEBAAAAAQcHAADXAgAgqgEBAAAAAa4BQAAAAAHLAQEAAAABzAEBAAAAAc0BAQAAAAHPAQAAAM8BAgIAAAALACAbAACWAwAgAwAAAAsAIBsAAJYDACAcAACVAwAgARQAAPUDADAMBwAAqAIAIAgAAKsCACCnAQAArwIAMKgBAAAJABCpAQAArwIAMKoBAQAAAAGuAUAA_QEAIcgBAQD8AQAhywEBAPwBACHMAQEA_AEAIc0BAQD8AQAhzwEAALACzwEiAgAAAAsAIBQAAJUDACACAAAAkwMAIBQAAJQDACAKpwEAAJIDADCoAQAAkwMAEKkBAACSAwAwqgEBAPwBACGuAUAA_QEAIcgBAQD8AQAhywEBAPwBACHMAQEA_AEAIc0BAQD8AQAhzwEAALACzwEiCqcBAACSAwAwqAEAAJMDABCpAQAAkgMAMKoBAQD8AQAhrgFAAP0BACHIAQEA_AEAIcsBAQD8AQAhzAEBAPwBACHNAQEA_AEAIc8BAACwAs8BIgaqAQEAuAIAIa4BQAC5AgAhywEBALgCACHMAQEAuAIAIc0BAQC4AgAhzwEAANQCzwEiBwcAANUCACCqAQEAuAIAIa4BQAC5AgAhywEBALgCACHMAQEAuAIAIc0BAQC4AgAhzwEAANQCzwEiBwcAANcCACCqAQEAAAABrgFAAAAAAcsBAQAAAAHMAQEAAAABzQEBAAAAAc8BAAAAzwECDAEAAJgDACAJAACZAwAgCgAAmgMAIAsAAJsDACCqAQEAAAABrgFAAAAAAb0BAQAAAAHJAQgAAAAB1wEBAAAAAdgBAQAAAAHZAQgAAAAB2gEgAAAAAQMbAADzAwAg5QEAAPQDACDrAQAAAQAgBBsAAIsDADDlAQAAjAMAMOcBAACOAwAg6wEAAI8DADAEGwAA_wIAMOUBAACAAwAw5wEAAIIDACDrAQAAgwMAMAQbAADzAgAw5QEAAPQCADDnAQAA9gIAIOsBAAD3AgAwBBsAAOICADDlAQAA4wIAMOcBAADlAgAg6wEAAOYCADAAAAAAAAAFGwAA7gMAIBwAAPEDACDlAQAA7wMAIOYBAADwAwAg6wEAAFMAIAMbAADuAwAg5QEAAO8DACDrAQAAUwAgAAAAAegBAAAA3gECBxsAANgDACAcAADbAwAg5QEAANkDACDmAQAA2gMAIOkBAAADACDqAQAAAwAg6wEAAAYAIAsbAADPAwAwHAAA0wMAMOUBAADQAwAw5gEAANEDADDnAQAA0gMAIOgBAACPAwAw6QEAAI8DADDqAQAAjwMAMOsBAACPAwAw7AEAANQDADDtAQAAkgMAMAsbAADGAwAwHAAAygMAMOUBAADHAwAw5gEAAMgDADDnAQAAyQMAIOgBAACDAwAw6QEAAIMDADDqAQAAgwMAMOsBAACDAwAw7AEAAMsDADDtAQAAhgMAMAsbAAC6AwAwHAAAvwMAMOUBAAC7AwAw5gEAALwDADDnAQAAvQMAIOgBAAC-AwAw6QEAAL4DADDqAQAAvgMAMOsBAAC-AwAw7AEAAMADADDtAQAAwQMAMAsbAACuAwAwHAAAswMAMOUBAACvAwAw5gEAALADADDnAQAAsQMAIOgBAACyAwAw6QEAALIDADDqAQAAsgMAMOsBAACyAwAw7AEAALQDADDtAQAAtQMAMAyqAQEAAAABrgFAAAAAAa8BQAAAAAG7AQEAAAABvAEBAAAAAb4BAQAAAAG_AQEAAAABwAEBAAAAAcEBQAAAAAHCAUAAAAABwwEBAAAAAcQBAQAAAAECAAAAIAAgGwAAuQMAIAMAAAAgACAbAAC5AwAgHAAAuAMAIAEUAADtAwAwEQEAAKgCACCnAQAApgIAMKgBAAAeABCpAQAApgIAMKoBAQAAAAGuAUAA_QEAIa8BQAD9AQAhuwEBAPwBACG8AQEA_AEAIb0BAQD8AQAhvgEBAJ4CACG_AQEAngIAIcABAQCeAgAhwQFAAKcCACHCAUAApwIAIcMBAQCeAgAhxAEBAJ4CACECAAAAIAAgFAAAuAMAIAIAAAC2AwAgFAAAtwMAIBCnAQAAtQMAMKgBAAC2AwAQqQEAALUDADCqAQEA_AEAIa4BQAD9AQAhrwFAAP0BACG7AQEA_AEAIbwBAQD8AQAhvQEBAPwBACG-AQEAngIAIb8BAQCeAgAhwAEBAJ4CACHBAUAApwIAIcIBQACnAgAhwwEBAJ4CACHEAQEAngIAIRCnAQAAtQMAMKgBAAC2AwAQqQEAALUDADCqAQEA_AEAIa4BQAD9AQAhrwFAAP0BACG7AQEA_AEAIbwBAQD8AQAhvQEBAPwBACG-AQEAngIAIb8BAQCeAgAhwAEBAJ4CACHBAUAApwIAIcIBQACnAgAhwwEBAJ4CACHEAQEAngIAIQyqAQEAuAIAIa4BQAC5AgAhrwFAALkCACG7AQEAuAIAIbwBAQC4AgAhvgEBAL4CACG_AQEAvgIAIcABAQC-AgAhwQFAAL8CACHCAUAAvwIAIcMBAQC-AgAhxAEBAL4CACEMqgEBALgCACGuAUAAuQIAIa8BQAC5AgAhuwEBALgCACG8AQEAuAIAIb4BAQC-AgAhvwEBAL4CACHAAQEAvgIAIcEBQAC_AgAhwgFAAL8CACHDAQEAvgIAIcQBAQC-AgAhDKoBAQAAAAGuAUAAAAABrwFAAAAAAbsBAQAAAAG8AQEAAAABvgEBAAAAAb8BAQAAAAHAAQEAAAABwQFAAAAAAcIBQAAAAAHDAQEAAAABxAEBAAAAAQeqAQEAAAABrQFAAAAAAa4BQAAAAAGvAUAAAAABxQEBAAAAAcYBAQAAAAHHAQEAAAABAgAAABwAIBsAAMUDACADAAAAHAAgGwAAxQMAIBwAAMQDACABFAAA7AMAMAwBAACoAgAgpwEAAKkCADCoAQAAGgAQqQEAAKkCADCqAQEAAAABrQFAAP0BACGuAUAA_QEAIa8BQAD9AQAhvQEBAPwBACHFAQEAAAABxgEBAJ4CACHHAQEAngIAIQIAAAAcACAUAADEAwAgAgAAAMIDACAUAADDAwAgC6cBAADBAwAwqAEAAMIDABCpAQAAwQMAMKoBAQD8AQAhrQFAAP0BACGuAUAA_QEAIa8BQAD9AQAhvQEBAPwBACHFAQEA_AEAIcYBAQCeAgAhxwEBAJ4CACELpwEAAMEDADCoAQAAwgMAEKkBAADBAwAwqgEBAPwBACGtAUAA_QEAIa4BQAD9AQAhrwFAAP0BACG9AQEA_AEAIcUBAQD8AQAhxgEBAJ4CACHHAQEAngIAIQeqAQEAuAIAIa0BQAC5AgAhrgFAALkCACGvAUAAuQIAIcUBAQC4AgAhxgEBAL4CACHHAQEAvgIAIQeqAQEAuAIAIa0BQAC5AgAhrgFAALkCACGvAUAAuQIAIcUBAQC4AgAhxgEBAL4CACHHAQEAvgIAIQeqAQEAAAABrQFAAAAAAa4BQAAAAAGvAUAAAAABxQEBAAAAAcYBAQAAAAHHAQEAAAABBggAANACACCqAQEAAAABrgFAAAAAAcgBAQAAAAHJAQIAAAABygEBAAAAAQIAAAAPACAbAADOAwAgAwAAAA8AIBsAAM4DACAcAADNAwAgARQAAOsDADACAAAADwAgFAAAzQMAIAIAAACHAwAgFAAAzAMAIAWqAQEAuAIAIa4BQAC5AgAhyAEBALgCACHJAQIAzAIAIcoBAQC4AgAhBggAAM4CACCqAQEAuAIAIa4BQAC5AgAhyAEBALgCACHJAQIAzAIAIcoBAQC4AgAhBggAANACACCqAQEAAAABrgFAAAAAAcgBAQAAAAHJAQIAAAABygEBAAAAAQcIAADYAgAgqgEBAAAAAa4BQAAAAAHIAQEAAAABzAEBAAAAAc0BAQAAAAHPAQAAAM8BAgIAAAALACAbAADXAwAgAwAAAAsAIBsAANcDACAcAADWAwAgARQAAOoDADACAAAACwAgFAAA1gMAIAIAAACTAwAgFAAA1QMAIAaqAQEAuAIAIa4BQAC5AgAhyAEBALgCACHMAQEAuAIAIc0BAQC4AgAhzwEAANQCzwEiBwgAANYCACCqAQEAuAIAIa4BQAC5AgAhyAEBALgCACHMAQEAuAIAIc0BAQC4AgAhzwEAANQCzwEiBwgAANgCACCqAQEAAAABrgFAAAAAAcgBAQAAAAHMAQEAAAABzQEBAAAAAc8BAAAAzwECDAYAAKQDACAJAACZAwAgCgAAmgMAIAsAAJsDACCqAQEAAAABrgFAAAAAAckBCAAAAAHXAQEAAAAB2AEBAAAAAdkBCAAAAAHaASAAAAAB2wEBAAAAAQIAAAAGACAbAADYAwAgAwAAAAMAIBsAANgDACAcAADcAwAgDgAAAAMAIAYAAKMDACAJAADwAgAgCgAA8QIAIAsAAPICACAUAADcAwAgqgEBALgCACGuAUAAuQIAIckBCADsAgAh1wEBAL4CACHYAQEAvgIAIdkBCADsAgAh2gEgAO0CACHbAQEAuAIAIQwGAACjAwAgCQAA8AIAIAoAAPECACALAADyAgAgqgEBALgCACGuAUAAuQIAIckBCADsAgAh1wEBAL4CACHYAQEAvgIAIdkBCADsAgAh2gEgAO0CACHbAQEAuAIAIQMbAADYAwAg5QEAANkDACDrAQAABgAgBBsAAM8DADDlAQAA0AMAMOcBAADSAwAg6wEAAI8DADAEGwAAxgMAMOUBAADHAwAw5wEAAMkDACDrAQAAgwMAMAQbAAC6AwAw5QEAALsDADDnAQAAvQMAIOsBAAC-AwAwBBsAAK4DADDlAQAArwMAMOcBAACxAwAg6wEAALIDADAHAQAA5wMAIAYAAOgDACAJAADjAwAgCgAA5AMAIAsAAOkDACDXAQAAugIAINgBAAC6AgAgAAAAAAkJAADjAwAgCgAA5AMAIAwAAOIDACANAADlAwAgDgAA5gMAIMQBAAC6AgAgzwEAALoCACDYAQAAugIAIOEBAAC6AgAgAQQAAJ0DACAABqoBAQAAAAGuAUAAAAAByAEBAAAAAcwBAQAAAAHNAQEAAAABzwEAAADPAQIFqgEBAAAAAa4BQAAAAAHIAQEAAAAByQECAAAAAcoBAQAAAAEHqgEBAAAAAa0BQAAAAAGuAUAAAAABrwFAAAAAAcUBAQAAAAHGAQEAAAABxwEBAAAAAQyqAQEAAAABrgFAAAAAAa8BQAAAAAG7AQEAAAABvAEBAAAAAb4BAQAAAAG_AQEAAAABwAEBAAAAAcEBQAAAAAHCAUAAAAABwwEBAAAAAcQBAQAAAAECqgEBAAAAAdMBAQAAAAECAAAAUwAgGwAA7gMAIAMAAABWACAbAADuAwAgHAAA8gMAIAQAAABWACAUAADyAwAgqgEBALgCACHTAQEAuAIAIQKqAQEAuAIAIdMBAQC4AgAhEAkAAN4DACAKAADfAwAgDQAA4AMAIA4AAOEDACCqAQEAAAABrgFAAAAAAa8BQAAAAAHEAQEAAAABzwEBAAAAAdMBAQAAAAHYAQEAAAAB3AEBAAAAAd4BAAAA3gEC3wEgAAAAAeABIAAAAAHhAQEAAAABAgAAAAEAIBsAAPMDACAGqgEBAAAAAa4BQAAAAAHLAQEAAAABzAEBAAAAAc0BAQAAAAHPAQAAAM8BAgWqAQEAAAABrgFAAAAAAb0BAQAAAAHJAQIAAAABygEBAAAAAQSqAQEAAAAB0AEBAAAAAdEBAQAAAAHSAQEAAAABAwAAACcAIBsAAPMDACAcAAD6AwAgEgAAACcAIAkAAKoDACAKAACrAwAgDQAArAMAIA4AAK0DACAUAAD6AwAgqgEBALgCACGuAUAAuQIAIa8BQAC5AgAhxAEBAL4CACHPAQEAvgIAIdMBAQC4AgAh2AEBAL4CACHcAQEAuAIAId4BAACoA94BIt8BIADtAgAh4AEgAO0CACHhAQEAvgIAIRAJAACqAwAgCgAAqwMAIA0AAKwDACAOAACtAwAgqgEBALgCACGuAUAAuQIAIa8BQAC5AgAhxAEBAL4CACHPAQEAvgIAIdMBAQC4AgAh2AEBAL4CACHcAQEAuAIAId4BAACoA94BIt8BIADtAgAh4AEgAO0CACHhAQEAvgIAIQiqAQEAAAABrgFAAAAAAb0BAQAAAAHJAQgAAAAB1wEBAAAAAdgBAQAAAAHZAQgAAAAB2gEgAAAAAQ0BAACYAwAgBgAApAMAIAkAAJkDACAKAACaAwAgqgEBAAAAAa4BQAAAAAG9AQEAAAAByQEIAAAAAdcBAQAAAAHYAQEAAAAB2QEIAAAAAdoBIAAAAAHbAQEAAAABAgAAAAYAIBsAAPwDACADAAAAAwAgGwAA_AMAIBwAAIAEACAPAAAAAwAgAQAA7wIAIAYAAKMDACAJAADwAgAgCgAA8QIAIBQAAIAEACCqAQEAuAIAIa4BQAC5AgAhvQEBALgCACHJAQgA7AIAIdcBAQC-AgAh2AEBAL4CACHZAQgA7AIAIdoBIADtAgAh2wEBALgCACENAQAA7wIAIAYAAKMDACAJAADwAgAgCgAA8QIAIKoBAQC4AgAhrgFAALkCACG9AQEAuAIAIckBCADsAgAh1wEBAL4CACHYAQEAvgIAIdkBCADsAgAh2gEgAO0CACHbAQEAuAIAIQ0BAACYAwAgBgAApAMAIAoAAJoDACALAACbAwAgqgEBAAAAAa4BQAAAAAG9AQEAAAAByQEIAAAAAdcBAQAAAAHYAQEAAAAB2QEIAAAAAdoBIAAAAAHbAQEAAAABAgAAAAYAIBsAAIEEACAQCgAA3wMAIAwAAN0DACANAADgAwAgDgAA4QMAIKoBAQAAAAGuAUAAAAABrwFAAAAAAcQBAQAAAAHPAQEAAAAB0wEBAAAAAdgBAQAAAAHcAQEAAAAB3gEAAADeAQLfASAAAAAB4AEgAAAAAeEBAQAAAAECAAAAAQAgGwAAgwQAIAMAAAADACAbAACBBAAgHAAAhwQAIA8AAAADACABAADvAgAgBgAAowMAIAoAAPECACALAADyAgAgFAAAhwQAIKoBAQC4AgAhrgFAALkCACG9AQEAuAIAIckBCADsAgAh1wEBAL4CACHYAQEAvgIAIdkBCADsAgAh2gEgAO0CACHbAQEAuAIAIQ0BAADvAgAgBgAAowMAIAoAAPECACALAADyAgAgqgEBALgCACGuAUAAuQIAIb0BAQC4AgAhyQEIAOwCACHXAQEAvgIAIdgBAQC-AgAh2QEIAOwCACHaASAA7QIAIdsBAQC4AgAhAwAAACcAIBsAAIMEACAcAACKBAAgEgAAACcAIAoAAKsDACAMAACpAwAgDQAArAMAIA4AAK0DACAUAACKBAAgqgEBALgCACGuAUAAuQIAIa8BQAC5AgAhxAEBAL4CACHPAQEAvgIAIdMBAQC4AgAh2AEBAL4CACHcAQEAuAIAId4BAACoA94BIt8BIADtAgAh4AEgAO0CACHhAQEAvgIAIRAKAACrAwAgDAAAqQMAIA0AAKwDACAOAACtAwAgqgEBALgCACGuAUAAuQIAIa8BQAC5AgAhxAEBAL4CACHPAQEAvgIAIdMBAQC4AgAh2AEBAL4CACHcAQEAuAIAId4BAACoA94BIt8BIADtAgAh4AEgAO0CACHhAQEAvgIAIQ0BAACYAwAgBgAApAMAIAkAAJkDACALAACbAwAgqgEBAAAAAa4BQAAAAAG9AQEAAAAByQEIAAAAAdcBAQAAAAHYAQEAAAAB2QEIAAAAAdoBIAAAAAHbAQEAAAABAgAAAAYAIBsAAIsEACAQCQAA3gMAIAwAAN0DACANAADgAwAgDgAA4QMAIKoBAQAAAAGuAUAAAAABrwFAAAAAAcQBAQAAAAHPAQEAAAAB0wEBAAAAAdgBAQAAAAHcAQEAAAAB3gEAAADeAQLfASAAAAAB4AEgAAAAAeEBAQAAAAECAAAAAQAgGwAAjQQAIAMAAAADACAbAACLBAAgHAAAkQQAIA8AAAADACABAADvAgAgBgAAowMAIAkAAPACACALAADyAgAgFAAAkQQAIKoBAQC4AgAhrgFAALkCACG9AQEAuAIAIckBCADsAgAh1wEBAL4CACHYAQEAvgIAIdkBCADsAgAh2gEgAO0CACHbAQEAuAIAIQ0BAADvAgAgBgAAowMAIAkAAPACACALAADyAgAgqgEBALgCACGuAUAAuQIAIb0BAQC4AgAhyQEIAOwCACHXAQEAvgIAIdgBAQC-AgAh2QEIAOwCACHaASAA7QIAIdsBAQC4AgAhAwAAACcAIBsAAI0EACAcAACUBAAgEgAAACcAIAkAAKoDACAMAACpAwAgDQAArAMAIA4AAK0DACAUAACUBAAgqgEBALgCACGuAUAAuQIAIa8BQAC5AgAhxAEBAL4CACHPAQEAvgIAIdMBAQC4AgAh2AEBAL4CACHcAQEAuAIAId4BAACoA94BIt8BIADtAgAh4AEgAO0CACHhAQEAvgIAIRAJAACqAwAgDAAAqQMAIA0AAKwDACAOAACtAwAgqgEBALgCACGuAUAAuQIAIa8BQAC5AgAhxAEBAL4CACHPAQEAvgIAIdMBAQC4AgAh2AEBAL4CACHcAQEAuAIAId4BAACoA94BIt8BIADtAgAh4AEgAO0CACHhAQEAvgIAIRAJAADeAwAgCgAA3wMAIAwAAN0DACAOAADhAwAgqgEBAAAAAa4BQAAAAAGvAUAAAAABxAEBAAAAAc8BAQAAAAHTAQEAAAAB2AEBAAAAAdwBAQAAAAHeAQAAAN4BAt8BIAAAAAHgASAAAAAB4QEBAAAAAQIAAAABACAbAACVBAAgAwAAACcAIBsAAJUEACAcAACZBAAgEgAAACcAIAkAAKoDACAKAACrAwAgDAAAqQMAIA4AAK0DACAUAACZBAAgqgEBALgCACGuAUAAuQIAIa8BQAC5AgAhxAEBAL4CACHPAQEAvgIAIdMBAQC4AgAh2AEBAL4CACHcAQEAuAIAId4BAACoA94BIt8BIADtAgAh4AEgAO0CACHhAQEAvgIAIRAJAACqAwAgCgAAqwMAIAwAAKkDACAOAACtAwAgqgEBALgCACGuAUAAuQIAIa8BQAC5AgAhxAEBAL4CACHPAQEAvgIAIdMBAQC4AgAh2AEBAL4CACHcAQEAuAIAId4BAACoA94BIt8BIADtAgAh4AEgAO0CACHhAQEAvgIAIRAJAADeAwAgCgAA3wMAIAwAAN0DACANAADgAwAgqgEBAAAAAa4BQAAAAAGvAUAAAAABxAEBAAAAAc8BAQAAAAHTAQEAAAAB2AEBAAAAAdwBAQAAAAHeAQAAAN4BAt8BIAAAAAHgASAAAAAB4QEBAAAAAQIAAAABACAbAACaBAAgAwAAACcAIBsAAJoEACAcAACeBAAgEgAAACcAIAkAAKoDACAKAACrAwAgDAAAqQMAIA0AAKwDACAUAACeBAAgqgEBALgCACGuAUAAuQIAIa8BQAC5AgAhxAEBAL4CACHPAQEAvgIAIdMBAQC4AgAh2AEBAL4CACHcAQEAuAIAId4BAACoA94BIt8BIADtAgAh4AEgAO0CACHhAQEAvgIAIRAJAACqAwAgCgAAqwMAIAwAAKkDACANAACsAwAgqgEBALgCACGuAUAAuQIAIa8BQAC5AgAhxAEBAL4CACHPAQEAvgIAIdMBAQC4AgAh2AEBAL4CACHcAQEAuAIAId4BAACoA94BIt8BIADtAgAh4AEgAO0CACHhAQEAvgIAIQYFAAsJGAUKGQYMBAINHQkOIQoGAQABBQAIBgADCQwFChAGCxQHAgQHAgUABAEECAACBwABCAACAgEAAQgAAgEIAAIDCRUAChYACxcAAQEAAQEBAAEECSIACiMADSQADiUAAAAAAwUAECEAESIAEgAAAAMFABAhABEiABICAQABBgADAgEAAQYAAwUFABchABoiABszABg0ABkAAAAAAAUFABchABoiABszABg0ABkAAAMFACAhACEiACIAAAADBQAgIQAhIgAiAQgAAgEIAAIDBQAnIQAoIgApAAAAAwUAJyEAKCIAKQIHAAEIAAICBwABCAACAwUALiEALyIAMAAAAAMFAC4hAC8iADACAQABCAACAgEAAQgAAgUFADUhADgiADkzADY0ADcAAAAAAAUFADUhADgiADkzADY0ADcBAQABAQEAAQMFAD4hAD8iAEAAAAADBQA-IQA_IgBAAQEAAQEBAAEDBQBFIQBGIgBHAAAAAwUARSEARiIARwAAAAMFAE0hAE4iAE8AAAADBQBNIQBOIgBPDwIBECYBESkBEioBEysBFS0BFi8MFzANGDIBGTQMGjUOHTYBHjcBHzgMIzsPJDwTJT0CJj4CJz8CKEACKUECKkMCK0UMLEYULUgCLkoML0sVMEwCMU0CMk4MNVEWNlIcN1QDOFUDOVgDOlkDO1oDPFwDPV4MPl8dP2EDQGMMQWQeQmUDQ2YDRGcMRWofRmsjR2wHSG0HSW4HSm8HS3AHTHIHTXQMTnUkT3cHUHkMUXolUnsHU3wHVH0MVYABJlaBASpXggEFWIMBBVmEAQVahQEFW4YBBVyIAQVdigEMXosBK1-NAQVgjwEMYZABLGKRAQVjkgEFZJMBDGWWAS1mlwExZ5gBBmiZAQZpmgEGapsBBmucAQZsngEGbaABDG6hATJvowEGcKUBDHGmATNypwEGc6gBBnSpAQx1rAE0dq0BOneuAQl4rwEJebABCXqxAQl7sgEJfLQBCX22AQx-twE7f7kBCYABuwEMgQG8ATyCAb0BCYMBvgEJhAG_AQyFAcIBPYYBwwFBhwHEAQqIAcUBCokBxgEKigHHAQqLAcgBCowBygEKjQHMAQyOAc0BQo8BzwEKkAHRAQyRAdIBQ5IB0wEKkwHUAQqUAdUBDJUB2AFElgHZAUiXAdsBSZgB3AFJmQHfAUmaAeABSZsB4QFJnAHjAUmdAeUBDJ4B5gFKnwHoAUmgAeoBDKEB6wFLogHsAUmjAe0BSaQB7gEMpQHxAUymAfIBUA"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer } = await import("buffer");
  const wasmArray = Buffer.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// generated/prisma/internal/prismaNamespace.ts
import * as runtime2 from "@prisma/client/runtime/client";
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var defineExtension = runtime2.Extensions.defineExtension;

// generated/prisma/client.ts
globalThis["__dirname"] = path.dirname(fileURLToPath(import.meta.url));
var PrismaClient = getPrismaClientClass();

// lib/prisma.ts
var connectionString = `${process.env.DATABASE_URL}`;
var adapter = new PrismaPg({ connectionString });
var prisma = new PrismaClient({ adapter });

// lib/auth.ts
import nodemailer from "nodemailer";
var transporter = nodemailer.createTransport({
  host: "smtp.gmail.com",
  port: 587,
  secure: false,
  // Use true for port 465, false for port 587
  auth: {
    user: process.env.APP_USER,
    pass: process.env.APP_PASS
  }
});
var auth = betterAuth({
  database: prismaAdapter(prisma, {
    provider: "postgresql"
    // or "mysql", "postgresql", ...etc
  }),
  trustedOrigins: [process.env.APP_URL],
  user: {
    additionalFields: {
      role: {
        type: "string",
        defaultValue: "STUDENT",
        required: false
      },
      phone: {
        type: "string",
        required: false
      },
      status: {
        type: "string",
        defaultValue: "ACTIVE",
        required: false
      }
    }
  },
  emailAndPassword: {
    enabled: true,
    autoSignIn: true,
    requireEmailVerification: true
  },
  emailVerification: {
    sendOnSignUp: true,
    autoSignInAfterVerification: true,
    sendVerificationEmail: async ({ user, url, token }, request) => {
      try {
        const verificationUrl = `${process.env.APP_URL}/verify-email?token=${token}`;
        const info = await transporter.sendMail({
          from: '"Prisma Blog" <prismablog@ph.com>',
          to: user.email,
          subject: "Please verify your email!",
          html: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Email Verification</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      background-color: #f4f6f8;
      font-family: Arial, Helvetica, sans-serif;
    }

    .container {
      max-width: 600px;
      margin: 40px auto;
      background-color: #ffffff;
      border-radius: 8px;
      overflow: hidden;
      box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);
    }

    .header {
      background-color: #0f172a;
      color: #ffffff;
      padding: 20px;
      text-align: center;
    }

    .header h1 {
      margin: 0;
      font-size: 22px;
    }

    .content {
      padding: 30px;
      color: #334155;
      line-height: 1.6;
    }

    .content h2 {
      margin-top: 0;
      font-size: 20px;
      color: #0f172a;
    }

    .button-wrapper {
      text-align: center;
      margin: 30px 0;
    }

    .verify-button {
      background-color: #2563eb;
      color: #ffffff !important;
      padding: 14px 28px;
      text-decoration: none;
      font-weight: bold;
      border-radius: 6px;
      display: inline-block;
    }

    .verify-button:hover {
      background-color: #1d4ed8;
    }

    .footer {
      background-color: #f1f5f9;
      padding: 20px;
      text-align: center;
      font-size: 13px;
      color: #64748b;
    }

    .link {
      word-break: break-all;
      font-size: 13px;
      color: #2563eb;
    }
  </style>
</head>
<body>
  <div class="container">
    <!-- Header -->
    <div class="header">
      <h1>Prisma Blog</h1>
    </div>

    <!-- Content -->
    <div class="content">
      <h2>Verify Your Email Address</h2>
      <p>
        Hello ${user.name} <br /><br />
        Thank you for registering on <strong>Prisma Blog</strong>.
        Please confirm your email address to activate your account.
      </p>

      <div class="button-wrapper">
        <a href="${verificationUrl}" class="verify-button">
          Verify Email
        </a>
      </div>

      <p>
        If the button doesn\u2019t work, copy and paste the link below into your browser:
      </p>

      <p class="link">
        ${url}
      </p>

      <p>
        This verification link will expire soon for security reasons.
        If you did not create an account, you can safely ignore this email.
      </p>

      <p>
        Regards, <br />
        <strong>Prisma Blog Team</strong>
      </p>
    </div>

    <!-- Footer -->
    <div class="footer">
      \xA9 2025 Prisma Blog. All rights reserved.
    </div>
  </div>
</body>
</html>
`
        });
        console.log("Message sent:", info.messageId, user, url, token);
      } catch (err) {
        console.error(err);
        throw err;
      }
    }
  },
  socialProviders: {
    google: {
      prompt: "select_account consent",
      accessType: "offline",
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET
    }
  }
});

// src/app.ts
import cors from "cors";

// src/modules/tutor/tutor.route.ts
import express from "express";

// src/modules/tutor/tutor.service.ts
var createTutor = async (payload) => {
  const { user, bio, hourlyRate, categoryId } = payload;
  if (!user) {
    throw new Error("Unauthorized");
  }
  const existing = await prisma.tutorProfile.findUnique({
    where: {
      userId: user.id
    }
  });
  if (existing) {
    throw new Error("Tutor profile already exists");
  }
  return prisma.tutorProfile.create({
    data: {
      bio,
      hourlyRate,
      categoryId,
      userId: user.id,
      image: user.image
    }
  });
};
var getTutors = async (query) => {
  console.log(query);
  const { search, category, minRating, maxPrice } = query;
  return prisma.tutorProfile.findMany({
    where: {
      AND: [
        // SEARCH
        search ? {
          OR: [
            {
              user: {
                name: {
                  contains: search,
                  mode: "insensitive"
                }
              }
            },
            {
              bio: {
                contains: search,
                mode: "insensitive"
              }
            },
            {
              category: {
                name: {
                  contains: search,
                  mode: "insensitive"
                }
              }
            }
          ]
        } : {},
        // CATEGORY
        category ? {
          category: {
            name: {
              contains: category,
              mode: "insensitive"
            }
          }
        } : {},
        // MIN RATING
        minRating ? {
          rating: {
            gte: Number(minRating)
          }
        } : {},
        // MAX PRICE
        maxPrice ? {
          hourlyRate: {
            lte: Number(maxPrice)
          }
        } : {}
      ]
    },
    include: {
      user: {
        select: {
          id: true,
          name: true,
          email: true
        }
      },
      category: true
    }
  });
};
var updateTutor = async (userId, payload) => {
  return prisma.tutorProfile.update({
    where: { userId },
    data: payload
  });
};
var Availability = async (tutorId, payload) => {
  return prisma.availability.create({
    data: {
      tutorId,
      day: payload.day,
      startTime: payload.startTime,
      endTime: payload.endTime
    }
  });
};
var getTutorSessionsService = async (userId) => {
  const tutor = await prisma.tutorProfile.findUnique({
    where: {
      userId
    },
    select: {
      id: true
    }
  });
  if (!tutor) {
    throw new Error("Tutor not found");
  }
  const sessions = await prisma.booking.findMany({
    where: {
      tutorId: tutor.id
    },
    include: {
      student: true
    },
    orderBy: {
      createdAt: "desc"
    }
  });
  return sessions;
};

// src/modules/tutor/tutor.controller.ts
var createTutorController = async (req, res) => {
  try {
    const user = req.user;
    const tutor = await createTutor({
      user,
      ...req.body
    });
    res.status(200).json({
      status: true,
      message: "Tutor fetched successfully",
      data: tutor
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};
var getTutorsController = async (req, res) => {
  try {
    const tutors = await getTutors(req.query);
    console.log(tutors);
    res.status(200).json({
      status: true,
      message: "Tutors fetched successfully",
      data: tutors
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};
var updateTutorProfileController = async (req, res) => {
  try {
    const user = req.user;
    console.log(user);
    const tutor = await updateTutor(
      user.id,
      req.body
    );
    res.status(200).json({
      status: true,
      message: "Profile is updated",
      data: tutor
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};
var AvailabilityController = async (req, res) => {
  try {
    const user = req.user;
    const tutorProfile = await prisma.tutorProfile.findUnique({
      where: {
        userId: user.id
      }
    });
    if (!tutorProfile) {
      return res.status(404).json({
        success: false,
        message: "Tutor profile not found"
      });
    }
    const result = await Availability(
      tutorProfile.id,
      req.body
    );
    return res.status(200).json({
      success: true,
      message: "Availability updated",
      data: result
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: error.message
    });
  }
};
var getTutorSessions = async (req, res) => {
  try {
    const user = req.user;
    if (!user) {
      return res.status(401).json({
        success: false,
        message: "Unauthorized"
      });
    }
    const sessions = await getTutorSessionsService(user.id);
    return res.status(200).json({
      success: true,
      data: sessions
    });
  } catch (err) {
    return res.status(500).json({
      success: false,
      message: err.message
    });
  }
};

// src/midlewares/auth.middleware.ts
var authMiddleware = (...roles) => {
  return async (req, res, next) => {
    try {
      const session = await auth.api.getSession({
        headers: req.headers
      });
      if (!session) {
        return res.status(401).json({ message: "Unauthorized" });
      }
      req.user = session.user;
      console.log(req.user);
      if (roles.length && !roles.includes(req.user.role)) {
        return res.status(403).json({
          message: "Forbidden"
        });
      }
      next();
    } catch (error) {
      next(error);
    }
  };
};
var auth_middleware_default = authMiddleware;

// src/modules/tutor/tutor.route.ts
var router = express.Router();
router.get("/tutors", getTutorsController);
router.post(
  "/tutor/profile",
  auth_middleware_default("TUTOR" /* TUTOR */),
  createTutorController
);
router.put("/tutor/profile", auth_middleware_default("TUTOR" /* TUTOR */), updateTutorProfileController);
router.post("/tutor/availability", auth_middleware_default("TUTOR" /* TUTOR */), AvailabilityController);
router.get(
  "/sessions",
  auth_middleware_default("TUTOR" /* TUTOR */),
  getTutorSessions
);
var tutor_route_default = router;

// src/modules/category/category.route.ts
import express2 from "express";

// src/modules/category/category.service.ts
var createCategory = async (data) => {
  if (!data.name) {
    throw new Error("Category name is required");
  }
  const exists = await prisma.category.findUnique({
    where: { name: data.name }
  });
  if (exists) {
    throw new Error("Category already exists");
  }
  return prisma.category.create({
    data: {
      name: data.name
    }
  });
};
var getCategories = async () => {
  return prisma.category.findMany();
};

// src/modules/category/category.controller.ts
var createCategories = async (req, res) => {
  try {
    const result = await createCategory(req.body);
    res.status(201).json({
      status: true,
      message: "Categories created successfully",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: error.message
    });
  }
};
var getCategories2 = async (req, res) => {
  try {
    const categories = await getCategories();
    res.status(200).json({
      status: true,
      message: "Categories fetched successfully",
      data: categories
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};

// src/modules/category/category.route.ts
var router2 = express2.Router();
router2.post("/categories", auth_middleware_default("ADMIN" /* ADMIN */), createCategories);
router2.get("/categories", getCategories2);
var category_route_default = router2;

// src/modules/booking/booking.route.ts
import express3 from "express";

// src/modules/booking/booking.service.ts
var convertToMinutes = (time) => {
  const [hourMinute, modifier] = time.split(" ");
  let [hours, minutes] = hourMinute.split(":").map(Number);
  if (modifier === "PM" && hours !== 12) {
    hours += 12;
  }
  if (modifier === "AM" && hours === 12) {
    hours = 0;
  }
  return hours * 60 + minutes;
};
var createBooking = async (payload) => {
  const availability = await prisma.availability.findFirst({
    where: {
      tutorId: payload.tutorId,
      day: payload.day
    }
  });
  if (!availability) {
    throw new Error("Tutor not available on this day");
  }
  const bookingTime = convertToMinutes(payload.time);
  const startTime = convertToMinutes(availability.startTime);
  const endTime = convertToMinutes(availability.endTime);
  if (bookingTime < startTime || bookingTime > endTime) {
    throw new Error("Tutor not available");
  }
  const existingBooking = await prisma.booking.findFirst({
    where: {
      tutorId: payload.tutorId,
      date: payload.date,
      time: payload.time
    }
  });
  if (existingBooking) {
    throw new Error("This slot already booked");
  }
  const { day, ...bookingData } = payload;
  return prisma.booking.create({
    data: bookingData
  });
};
var getMyBookings = async (userId) => {
  return await prisma.booking.findMany({
    where: {
      studentId: userId
    },
    include: {
      tutor: {
        include: {
          user: true,
          category: true
        }
      }
    },
    orderBy: {
      createdAt: "desc"
    }
  });
};
var getBookingById = async (id) => {
  return prisma.booking.findUnique({
    where: { id },
    include: {
      tutor: true,
      student: true
    }
  });
};
var getAllBookingsService = async () => {
  const bookings = await prisma.booking.findMany({
    orderBy: {
      createdAt: "desc"
    }
  });
  const userIds = bookings.map((b) => b.studentId);
  const tutorIds = bookings.map((b) => b.tutorId);
  const users = await prisma.user.findMany({
    where: {
      id: { in: userIds }
    },
    select: {
      id: true,
      name: true,
      image: true,
      email: true
    }
  });
  const tutors = await prisma.tutorProfile.findMany({
    where: {
      id: { in: tutorIds }
    },
    include: {
      user: {
        select: {
          name: true,
          image: true,
          email: true
        }
      },
      category: {
        select: {
          name: true
        }
      }
    }
  });
  const result = bookings.map((b) => {
    return {
      ...b,
      student: users.find((u) => u.id === b.studentId),
      tutor: tutors.find((t) => t.id === b.tutorId)
    };
  });
  return result;
};

// src/modules/booking/booking.controller.ts
var createBooking2 = async (req, res) => {
  try {
    const user = req.user;
    if (!user) {
      return res.status(401).json({
        success: false,
        message: "Unauthorized"
      });
    }
    const booking = await createBooking({
      studentId: user.id,
      ...req.body
    });
    res.status(201).json({
      success: true,
      message: "Booking created",
      data: booking
    });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};
var getMyBookings2 = async (req, res) => {
  try {
    const user = req.user;
    if (!user) {
      return res.status(401).json({
        success: false,
        message: "Unauthorized"
      });
    }
    const bookings = await getMyBookings(
      user.id
    );
    return res.status(200).json({
      success: true,
      message: "My bookings fetched successfully",
      data: bookings
    });
  } catch (err) {
    return res.status(500).json({
      success: false,
      message: err.message || "Internal Server Error"
    });
  }
};
var getBookingById2 = async (req, res) => {
  try {
    const id = req.params.id;
    const user = req.user;
    const bookings = await getBookingById(id);
    res.json({ success: true, data: bookings });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};
var getAllBookingsController = async (req, res) => {
  try {
    const bookings = await getAllBookingsService();
    return res.status(200).json({
      success: true,
      data: bookings
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: error.message || "Failed to fetch bookings"
    });
  }
};

// src/modules/booking/booking.route.ts
var router3 = express3.Router();
router3.post(
  "/bookings",
  auth_middleware_default("STUDENT" /* STUDENT */),
  createBooking2
);
router3.get(
  "/admin/bookings",
  auth_middleware_default("ADMIN" /* ADMIN */),
  getAllBookingsController
);
router3.get("/bookings", auth_middleware_default(), getMyBookings2);
router3.get("/bookings/:id", auth_middleware_default(), getBookingById2);
var booking_route_default = router3;

// src/modules/review/review.route.ts
import express4 from "express";

// src/modules/review/review.service.ts
var createReview = async (payload) => {
  const existingReview = await prisma.review.findFirst({
    where: {
      userId: payload.userId,
      tutorId: payload.tutorId
    }
  });
  if (existingReview) {
    return prisma.review.update({
      where: {
        id: existingReview.id
      },
      data: {
        comment: payload.comment,
        rating: payload.rating
      },
      include: {
        user: {
          select: {
            name: true,
            image: true
          }
        }
      }
    });
  }
  return prisma.review.create({
    data: payload,
    include: {
      user: {
        select: {
          name: true,
          image: true
        }
      }
    }
  });
};
var getTutorReviewsService = async (userId) => {
  const tutor = await prisma.tutorProfile.findUnique({
    where: {
      userId
    },
    select: {
      id: true
    }
  });
  if (!tutor) {
    throw new Error("Tutor not found");
  }
  const sessions = await prisma.review.findMany({
    where: {
      tutorId: tutor.id
    },
    include: {
      user: {
        select: {
          name: true,
          image: true,
          email: true
        }
      }
    },
    orderBy: {
      createdAt: "desc"
    }
  });
  return sessions;
};
var getPublicTutorReviewsService = async (tutorUserId) => {
  const tutor = await prisma.tutorProfile.findUnique({
    where: {
      id: tutorUserId
    },
    select: {
      id: true
    }
  });
  if (!tutor) {
    throw new Error("Tutor not found");
  }
  const reviews = await prisma.review.findMany({
    where: {
      tutorId: tutor.id
    },
    include: {
      user: {
        select: {
          name: true,
          image: true
        }
      }
    },
    orderBy: {
      createdAt: "desc"
    }
  });
  return reviews;
};

// src/modules/review/review.controller.ts
var createReview2 = async (req, res) => {
  try {
    const user = req.user;
    console.log(user);
    const review = await createReview({
      userId: user.id,
      ...req.body
    });
    return res.status(200).json({
      status: true,
      message: "Review created",
      data: review
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: error.message
    });
  }
};
var getTutorReviews = async (req, res) => {
  try {
    const user = req.user;
    if (!user) {
      return res.status(401).json({
        success: false,
        message: "Unauthorized"
      });
    }
    const reviews = await getTutorReviewsService(user.id);
    return res.status(200).json({
      success: true,
      data: reviews
    });
  } catch (err) {
    return res.status(500).json({
      success: false,
      message: err.message
    });
  }
};
var getPublicTutorReviews = async (req, res) => {
  try {
    const tutorUserIdRaw = req.params.tutorUserId;
    const tutorUserId = Array.isArray(tutorUserIdRaw) ? tutorUserIdRaw[0] : tutorUserIdRaw;
    const reviews = await getPublicTutorReviewsService(tutorUserId);
    return res.status(200).json({
      success: true,
      message: "Tutor reviews fetched successfully",
      data: reviews
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: error.message
    });
  }
};

// src/modules/review/review.route.ts
var router4 = express4.Router();
router4.post("/reviews", auth_middleware_default(), createReview2);
router4.get(
  "/reviews",
  auth_middleware_default("TUTOR" /* TUTOR */),
  getTutorReviews
);
router4.get("/reviews/:tutorUserId", getPublicTutorReviews);
var review_route_default = router4;

// src/modules/auth/auth.route.ts
import express5 from "express";

// src/modules/auth/auth.service.ts
var registerUser = async (data) => {
  const result = await auth.api.signUpEmail({
    body: {
      name: data.name,
      email: data.email,
      password: data.password,
      role: data.role,
      image: data.image
    }
  });
  return {
    success: true,
    message: "User registered",
    data: result
  };
};
var loginUser = async (data) => {
  const result = await auth.api.signInEmail({
    body: {
      email: data.email,
      password: data.password
    }
  });
  return {
    success: true,
    message: "Login success",
    data: result
  };
};
var getMe = async (headers) => {
  const session = await auth.api.getSession({ headers });
  return {
    success: true,
    data: session?.user
  };
};
var updateMe = async (userId, data) => {
  return prisma.user.update({
    where: {
      id: userId
    },
    data: {
      name: data.name,
      image: data.image
    }
  });
};

// src/modules/auth/auth.controller.ts
var registerUserController = async (req, res) => {
  const result = await registerUser(req.body);
  res.status(201).json(result);
};
var loginUserController = async (req, res) => {
  const result = await loginUser(req.body);
  res.status(200).json(result);
};
var getMeController = async (req, res) => {
  const result = await getMe(req.headers);
  res.json(result);
};
var updateMeController = async (req, res) => {
  const user = req.user;
  if (!user) {
    return res.status(401).json({
      success: false,
      message: "Unauthorized"
    });
  }
  const result = await updateMe(user.id, req.body);
  return res.status(200).json({
    success: true,
    message: "Profile updated successfully",
    data: result
  });
};

// src/modules/auth/auth.route.ts
var router5 = express5.Router();
router5.post("/register", registerUserController);
router5.post("/login", loginUserController);
router5.get("/me", auth_middleware_default(), getMeController);
router5.patch("/me", auth_middleware_default(), updateMeController);
var auth_route_default = router5;

// src/modules/admin/admin.route.ts
import express6 from "express";

// src/modules/admin/admin.service.ts
var getUsersService = async () => {
  const users = await prisma.user.findMany();
  return users;
};
var updateUserStatusService = async (id, status) => {
  const updatedUser = await prisma.user.update({
    where: {
      id
    },
    data: {
      status
    }
  });
  return updatedUser;
};

// src/modules/admin/admin.controller.ts
var getUsersController = async (req, res) => {
  try {
    const users = await getUsersService();
    return res.status(200).json({
      success: true,
      data: users
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: "Failed to fetch users"
    });
  }
};
var updateUserStatusController = async (req, res) => {
  try {
    const id = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
    const { status } = req.body;
    const updatedUser = await updateUserStatusService(
      id,
      status
    );
    return res.status(200).json({
      success: true,
      message: "User updated successfully",
      data: updatedUser
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: "Failed to update user"
    });
  }
};

// src/modules/admin/admin.route.ts
var router6 = express6.Router();
router6.get(
  "/admin/users",
  auth_middleware_default("ADMIN" /* ADMIN */),
  getUsersController
);
router6.patch(
  "/admin/users/:id",
  auth_middleware_default("ADMIN" /* ADMIN */),
  updateUserStatusController
);
var admin_route_default = router6;

// src/app.ts
var app = express7();
app.use(express7.json());
app.use(cors({
  origin: process.env.APP_URL || "http://localhost:3000",
  credentials: true
}));
app.use("/api/auth", toNodeHandler(auth));
app.use("/api", auth_route_default);
app.use("/api", tutor_route_default);
app.use("/api", category_route_default);
app.use("/api", booking_route_default);
app.use("/api", review_route_default);
app.use("/api", admin_route_default);
app.get("/", (req, res) => {
  res.send("Hello, World!");
});
var app_default = app;

// src/index.ts
var index_default = app_default;
export {
  index_default as default
};
